### ISSUE TITLE
[FEATURE]: New Donation form

### ISSUE THREAD

**Issue by 0xabdulkhalid** [MilanCommunity/Milan#1000]
### Description

- I would like to revamp the donation form on the clubs page, the current design of the form lacks proper padding and styling.

### Screenshots

| CURRENT STATE | DESIRED STATE V1| DESIRED STATE V2 |
| :---: | :---: | :---: |
| ![image](https://github.com/tamalCodes/Milan/assets/92252895/89a3de04-7ad3-416c-b7ea-ac51aaa7dd78) | ![Screenshot 2023-07-22 at 19-15-08 Milan](https://github.com/tamalCodes/Milan/assets/92252895/430aacf9-3c37-424a-85a6-d087621e5412) | ![Screenshot 2023-07-22 at 19-18-57 Milan](https://github.com/tamalCodes/Milan/assets/92252895/1090df7f-5825-460e-aa41-edf2ca374ec9) |

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by 0xabdulkhalid** [comment]
Hey there @tamalCodes 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by tamalCodes** [comment]
Hi @0xabdulkhalid , if you now visit: https://milanhub.org/clubs, you can see that we have re-vamped a lot of sections and the donate is now ON the card itself. The `Read more` part is not ready yet.

You can make a DonateModal from scratch, we do have a Modal component, make sure it aligns properly with our styles.

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
