### ISSUE TITLE
[FEATURE] Updation footer  

### ISSUE THREAD

**Issue by PatilHarshh** [MilanCommunity/Milan#1026]
### Description

Making Footer more Attractive giving more relavent links 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by PatilHarshh** [comment]
@tamalCodes please assign me

**Comment by kraggy09** [comment]
I can work on this. Pls assign me

**Comment by PatilHarshh** [comment]
Bro coding period is Over !

**Comment by tamalCodes** [comment]
@PatilHarshh Is this issue to be closed ?
