### ISSUE TITLE
[BUG] Change GitHub links & Contact

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1037]
### Description

So currently we have Links inside of our project which takes us to the GitHub repo of this project so that the users can contribute to it. However that link is not valid anymore. Also we have links in the footer to `contact` us. <br/>

Here's what that needs to be done: 

- Modify the github Links to the Link of this repository.
- Remove all the `Contact Us`.

<br/><br/>

> [!NOTE]
> This issue is a https://github.com/MilanCommunity/Milan/labels/good%20first%20issue , if you are a experienced developer please skip this one.

<br/>

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by motuncoded** [comment]
Can I work on this

**Comment by tamalCodes** [comment]
## 📚 Info

> [!NOTE]
> Branch to make a PR/Fork would be the `beta`


Hi @motuncoded, you can start working on the issue. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.




## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**

**Comment by priyanshtiwari001** [comment]
Hi @tamalCodes , This is still open, can I work on this?

**Comment by motuncoded** [comment]
Currently working on it will send the PR soon

**Comment by motuncoded** [comment]
![contact](https://github.com/MilanCommunity/Milan/assets/67984447/ccf04fe9-d1c6-4823-a362-0e1e8812dab0)


here is what I did

**Comment by motuncoded** [comment]
Is this right thing ?

**Comment by tamalCodes** [comment]
Hi @motuncoded , looks good to me - always make a PR and continue working and pushing commits there itself. Easier to track and converse.

**Comment by motuncoded** [comment]
Can we add other social links if available

**Comment by tamalCodes** [comment]
> Can we add other social links if available

As of now there ar no social links except Twitter and GitHub.

**Comment by madjed-hue** [comment]
Try changing Twitter to the new logo and name.
Good Luck

**Comment by motuncoded** [comment]
Thanks for the tip! Will do that

**Comment by tamalCodes** [comment]
Hi @motuncoded you have made 2 PRs for one single issue, can you please close one of them?

![image](https://github.com/MilanCommunity/Milan/assets/72851613/64334678-a7f0-431f-9a37-d7935344ce23)

**Comment by motuncoded** [comment]
ok
