### ISSUE TITLE
[FEATURE] Merge Authentication for different types of user

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1038]
### Description

So currently we have two different types of user. One of them is the `normal user` or `individual` and the other one is basically any kind of `club charity or organization`. </br>

Now the issue is it consists of a lot of different duplicacies like managing different states,  calling separate API's and so on.  If you would visit the [Club Registration](https://milanhub.org/clubs/register) and the [User registration](https://milanhub.org/user/register), you would notice that a lot of fields are the same like `Name` , `Address`, `Pincode` and so on. </br>

So it would be much better if we can merge these 2 types of authentication into 1 single page. Here's what that are to be done. 

- Merge authentication such that instead of that modal being open whenever we click on `Sign up`  it takes us to https://milanhub.org/user/register
- Inside of the authentication page we can have maybe a drop down which suggests what type of user is this.
- Based on that dropdown field we can then show/hide different forms.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/72851613/9b1abd0c-b8f4-42af-a18c-e747ec7ce754)

### 🥦 Browser

Opera

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by VanshVg** [comment]
Hey @tamalCodes I'd like to work on this issue.

**Comment by tamalCodes** [comment]
## 📚 Info

> [!NOTE]
> Branch to make a PR/Fork would be the `beta`


Hi @VanshVg , you can start working on the issue. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.




## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**

**Comment by VanshVg** [comment]
Yes, I have opened a PR now you can review it.
