### ISSUE TITLE
[BUG]  Incorrect usage of <h1> tag within <footer> element

### ISSUE THREAD

**Issue by badrivlog** [MilanCommunity/Milan#1039]
### Description

The current [components/Footer/Footer.jsx](https://github.com/MilanCommunity/Milan/blob/main/src/components/Footer/Footer.jsx) component contains instances where the `<h1>` tag is being used within the `<footer>` element. According to HTML5 standards, the `<footer>` element is typically reserved for footer content and information, while the `<h1>` tag is used for top-level headings. This structure might not be semantically appropriate and could affect the document's accessibility and readability.

**Expected Behavior:**
The usage of HTML elements should adhere to best practices and semantic guidelines to ensure proper document structure and accessibility.

**Actual Behavior:**
The `<h1>` tag is being utilized within `<footer>` elements, potentially causing confusion in terms of heading hierarchy and document structure.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by madjed-hue** [comment]
hey @badrivlog  
can I work on this issue ?

**Comment by tamalCodes** [comment]
## 📚 Info

> [!NOTE]
> Branch to make a PR/Fork would be the `beta`


Hi @badrivlog , you can start working on the issue. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.




## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**

**Comment by tamalCodes** [comment]
> * I am willing to work on this issue (blank for no).

Hi there, since the author has checked the `I am willing to work on this issue (blank for no).` box, I will let them work on it. Do join our org for more issues, or you can even make one of your own !
