### ISSUE TITLE
[BUG] Improve the steps on the main page

### ISSUE THREAD

**Issue by karthiknadar1204** [MilanCommunity/Milan#1053]
### Description

In the current design of the main page below the hero section, There are three steps that appear one after another in a line, I propose to improve the UI of this feature by doing the following:
1)So for step 1, I would put it in a container of colour that goes with the page, preferably orange, now instead of at the centre of the page, I will push step 1 i.e Collaborate to the left of the page inside the container, Now on the container, I will add border-radius to the top right and bottom right corner and place the contents of step 1 at the centre of the container horizontally and vertically.

2)I propose the same for steps 2 and 3 but will push them to the right and left side of the page with a changed border radius accordingly.

The animation of appearance will remain intact but the UI will look more interactive than now as it currently feels monotonous in a single line.

Please share your views for the same.
Thank you

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by karthiknadar1204** [comment]
I would like to work on ths issue

**Comment by tamalCodes** [comment]
Hi there, @karthiknadar1204, well I am not looking forward to changing the design but I would recommend a few things.

 - The numbers there are not to indicate any steps they were added just for design purposes. However, this can prove wildly misunderstood and yeah that can be removed.
 - The second thing is we are looking forward to reducing the size of the landing text, which is `Collaborate. Connect. Build.` it is at 100+ pixels.


Also in the mobile version of the web app we have this immense line gap which I think can be reduced for a good look.
![image](https://github.com/MilanCommunity/Milan/assets/72851613/f85ac646-ac83-4f4e-9c4d-525d3fd2b201)

**Comment by karthiknadar1204** [comment]
works, can take up the task

**Comment by tamalCodes** [comment]
> [!IMPORTANT]
> **The branch to make a PR/Fork would be `beta`**

</br>

Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.




## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR that are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop a email at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
