### ISSUE TITLE
[BUG] Go Back Button on Sign In Page 

### ISSUE THREAD

**Issue by Steakysteak** [MilanCommunity/Milan#1054]
### Description

The Button "Go back" navigates to the previous page not the home page. 

This Becomes a problem when we go to sign in but then select register, after this if we click "Go back" we have to click it multiple times to get to home page but this is not very convenient as the only place we can go back to is the home page.

I would like to work on this issue.   

### Screenshots

![Screenshot from 2023-08-23 11-50-43](https://github.com/MilanCommunity/Milan/assets/75496668/b25afe8c-cf7f-40f7-b6b0-07681f13a51c)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
> [!IMPORTANT]
> **The branch to make a PR/Fork would be `beta`**

</br>

Hi @Steakysteak , You can start working on the issue. The goal was actually to go back to the home page, but later we decided to just the previous page. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.




## 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**
