### ISSUE TITLE
[BUG] International Postal Code not accepted on register

### ISSUE THREAD

**Issue by Giuliano1993** [MilanCommunity/Milan#1055]
### Description

On Signing up, only 6 numbers zipcode is accepted.
As a matter of fact most postal codes in the world are 5 numbers long, so the field should result as valid even with a 5 numbers long code

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
> [!IMPORTANT]
> **The branch to make a PR to/ fork would be  `beta`**

<br/>

Hi @Giuliano1993 , you can start working on the issue.  I never considered this case TBH. Assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

<br/>

### 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**
