### ISSUE TITLE
Confirm Password validation is missing [BUG]

### ISSUE THREAD

**Issue by khushi89012** [MilanCommunity/Milan#1058]
### Description

Issue if we are writing the password and confirm Password while signup it is getting excepted
![image](https://github.com/MilanCommunity/Milan/assets/95909861/3df1a7b4-6465-45e9-9f72-af48bc01ef51)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by khushi89012** [comment]
Please check #1059

**Comment by tamalCodes** [comment]
Hi there @khushi89012 , please never create any Pull requests until and unless I have assigned you to do so. It's a waste of effort and time. In this case, we have already added such checks in the `useValidation` hook. It will show up once the user tries to sign up.

https://github.com/MilanCommunity/Milan/blob/a81262b8b0f090d598c0ec6618903dade135d8c3/src/hooks/useValidation.js#L22


and for stronger passwords we are working on #1044 which will resolve this issue. So unfortunately I will have close the PR as well as the issue.
