### ISSUE TITLE
Responsiveness and optimization problem mostly while loading

### ISSUE THREAD

**Issue by inbuilt-aura** [MilanCommunity/Milan#1060]
### Description

Responsiveness and optimization problem mostly while loading. While loading or refreshing or even desktop to mobile is a bit glitchy so can be improved.When user wants to go to other page,like events or any, websites gets stuck or sometimes even shows 404.

### Browser 🥦

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Can you please show me a working demo of this errors?

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
