### ISSUE TITLE
[BUG] Footer elements not centered on screens <768 pixels

### ISSUE THREAD

**Issue by badrivlog** [MilanCommunity/Milan#1072]
### Description

When accessing the https://milanhub.org/ on screens with a width less than 768 pixels, certain elements within the footer do not maintain their centered alignment as intended.

## Expected behavior:
The highlighted elements in the footer should be centered on the screen when the screen size is less than 768 pixels

### Screenshots

![milan](https://github.com/MilanCommunity/Milan/assets/73095526/148efc27-027a-4127-adae-2a2bf7890244)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Himanshu-Dhawale** [comment]
Can I work on this issue?

**Comment by khushi89012** [comment]
I would like to work on this

**Comment by tamalCodes** [comment]
Hi @khushi89012 , Currently @Utkarsh3128 is working on it !

**Comment by badrivlog** [comment]
@tamalCodes could I raise a PR for this issue as you assigned to me
