### ISSUE TITLE
💡Feature: Add an input field for `iframe` in signup

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1077]
### Description

Currently, if you visit the auth signup page (https://milanhub.org/auth/signup) you will notice that for the club's signup, an input for the iframe is missing.

 - Please add a field below `Pincode / Zipcode` labeled as `Iframe code`
 - Make sure that the data is validated through the [useValidation hook](https://github.com/MilanCommunity/Milan/blob/main/src/hooks/useValidation.js) when the user submits the data
 - Even though the backend for the same is not made yet, make sure it is passed to the backend.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/72851613/99ee67e0-beb0-4a95-9082-c7a19e4d090d)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by stoyanov-kaloyan** [comment]
I would like to work upon this issue.

**Comment by tamalCodes** [comment]
Hi @stoyanov-kaloyan , you can start working on the issue, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
