### ISSUE TITLE
[FEATURE] Add and Configure the `website` field

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1078]
### Description

Currently, if you visit the auth signup page (https://milanhub.org/auth/signup) you will notice that for the club's signup, an input for the website is missing even though we have it in the ClubDetails page.

 - Please add a field below `Club Description` labeled as `Club website`
 - Make sure that the data is validated through the [useValidation hook](https://github.com/MilanCommunity/Milan/blob/main/src/hooks/useValidation.js) when the user submits the data. The club website is optional.
 - Even though the backend for the same is not made yet, make sure it is passed to the backend.
 - Also apply it to the [details page](https://github.com/MilanCommunity/Milan/blob/ec29b4ab572c433b1561d2a95d35ebc03f65d970/src/pages/Club/Details/ClubDetails.jsx#L72C1-L72C1) such that the club's website is shown IF the user has a website.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/72851613/9fef5779-e2a2-4227-a2f2-2174da0e6631)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by YuvarajSingh-0** [comment]
@tamalCodes I would like to work on this issue. Could you please assign it to me?

**Comment by tamalCodes** [comment]
Hi @YuvarajSingh-0 , Thanks for showing interest in this issue as well, however, please complete #1070 first. Sometimes working on multiple issues can be time-consuming and difficult to track.

**Comment by stoyanov-kaloyan** [comment]
Hi @tamalCodes, I would like to work on this issue.
