### ISSUE TITLE
[BUG] issue with Report button in the footer

### ISSUE THREAD

**Issue by YuvarajSingh-0** [MilanCommunity/Milan#1080]
### Description

Report Button in the footer shows a blank screen after clicking. 

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @YuvarajSingh-0 , please complete #1079 first. Thanks.
