### ISSUE TITLE
🐞Bug: Website not responsive in some sections

### ISSUE THREAD

**Issue by RAHUL956777** [MilanCommunity/Milan#1083]
### Description

At the point of this screen size 875*774 to 501*774 website not responsive ...i think to work on it 

 

### Screenshots

![milan1](https://github.com/MilanCommunity/Milan/assets/77888604/aa69f2a3-8aaa-4bdd-bbc0-5bbe6fe44682)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi, you can start working on the issue, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by tamalCodes** [comment]
Hi @RAHUL956777 , are you still working on this issue ?

**Comment by ViSiOnOp19cr** [comment]
I would like to work on this issue assign me

**Comment by ViSiOnOp19cr** [comment]
@tamalCodes if u assign me soon i can get started working on this

**Comment by RAHUL956777** [comment]
please check the pr #1117
