### ISSUE TITLE
[BUG] Navbar Issue

### ISSUE THREAD

**Issue by Git21221** [MilanCommunity/Milan#1084]
### Description

I can fix this navbar problem.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/101005577/7b155acf-cbbe-4eaa-8586-feedce30cb81)

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @Git21221 , can you please elaborate on what Navbar issue are you talking about ?

**Comment by Git21221** [comment]
@tamalCodes now the issue is fixed so i am gonna close this issue
