### ISSUE TITLE
🐞Bug: Scroll to top button customization

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1088]
### Description

> [!IMPORTANT]  
> This is a very beginner-friendly issue. Please skip if you have some experience with development and OSS.

The scroll-up button turns transparent when someone hovers over it which is somewhat difficult to spot in places where we might have a dark background. Can you make sure the button is of the same color ?

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/72851613/5d772b94-734d-44f7-8afb-b625243cde1a)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by akinpinkman** [comment]
I can work on this issue. Kindly assign it to me.

**Comment by Shivangbhatnagar237** [comment]
Hello @tamalCodes, I would like to further discuss on this. 
The issue that you're referring to is that the button becomes transparent which leads to visibility issues on a dark background. So you want the button to consistently have a white background. Is this correct?

**Comment by tamalCodes** [comment]
Hi @Shivangbhatnagar237 , there might be a `hover` property on the button, it would be better if that property were to be removed.

**Comment by Shivangbhatnagar237** [comment]
Hey @tamalCodes, I think this hover property is causing the issue 
![image](https://github.com/MilanCommunity/Milan/assets/47966497/8b27ab77-eaf7-4c51-829c-f2737e834ab5)

After removing this hover property:
![image](https://github.com/MilanCommunity/Milan/assets/47966497/de3060ba-9c7e-428a-89c4-1239102db68e)
 
The button doesn't change and maintains the same styles.  Is this okay?
