### ISSUE TITLE
🐞Bug:  Social media icons not visible in footer

### ISSUE THREAD

**Issue by DON2604** [MilanCommunity/Milan#1090]
### Issue Description

The social links provided in the footer of our website are not functioning as expected. Currently, they are only visible when the user hovers over them, and even when clicked, they do not redirect users to their respective social media profiles.

### Issue Details

- **Visibility:** As of now, the social links in the footer are only visible when the user hovers over them. This behaviour is non-intuitive and can confuse users who expect to see direct links to our social media profiles without any additional interaction.

- **Non-Functional Links:** When users click on the social media icons in the footer, they are not redirected to the respective social media profiles. This renders the links essentially non-functional and fails to provide users with a seamless way to connect with us on social media.

### Expected Behavior

- The social links in the footer should be directly visible without requiring any user interaction such as hovering.
- Clicking on these links should seamlessly redirect users to the corresponding social media profiles.

### Steps to Reproduce

1. Visit the website's homepage.
2. Scroll to the bottom of the page to locate the footer section.
3. Observe that the social media icons (e.g., Twitter, Github, Contact Us) are not visible until the mouse is hovered over them.
4. Click on any of the social media icons in the footer.
5. Note that there is no redirection to the respective social media profiles.

### Proposed Solution

To resolve this issue, we should make the social media links directly visible in the footer without requiring any user interaction. Additionally, we must ensure that clicking these links redirects users to the correct social media profiles.

### Issue Creator

Mrinmay Das

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/89240074/8bd69e5c-cf3f-423d-858d-2bab5dad2c01)
![image](https://github.com/MilanCommunity/Milan/assets/89240074/204ca916-735f-420d-a285-ab709ac5fd43)
![image](https://github.com/MilanCommunity/Milan/assets/89240074/1ebad146-ae51-48e3-8d42-f53914de9484)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @DON2604 , you can start working on the issue, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
