### ISSUE TITLE
[🐞 BUG] Remove loading problem in events page

### ISSUE THREAD

**Issue by AbhiPatel10** [MilanCommunity/Milan#1095]
### Description

After some time, the loading appears on the events page; it should be removed or commented out.

Please also add Hacktoberfest label

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/76242769/4e6cc506-c4fa-45a1-b904-807dfc5c5ae5)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @AbhiPatel10 , you can start working on the issue, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
