### ISSUE TITLE
Remove Footer in Events Page

### ISSUE THREAD

**Issue by AbhiPatel10** [MilanCommunity/Milan#1096]
### Description

Currently Footer page is not require in Events page.

We can add later when event page  is fully work

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/76242769/4f407ed5-e63d-4f49-bee5-a69bf762e488)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by 100godmoon** [comment]
please assign me this issue

**Comment by 100godmoon** [comment]
I am willing to work on this issue #1096

**Comment by 100godmoon** [comment]
please assign me this issue

**Comment by tamalCodes** [comment]
Hi there, I don't see the need for this issue so I will be closing this shortly.
