### ISSUE TITLE
Feature: Make navbar scroll sensitive

### ISSUE THREAD

**Issue by Palakkgoyal** [MilanCommunity/Milan#1100]
### Description

I want to make the navbar such that when we scroll down it hides and when we scroll up it shows up again.
You can take demo of the feature from this website: https://blogzen-outerbase.netlify.app
Please assign this issue to me.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by AbhineshJha** [comment]
I am  interested in this issue , can you please assign this to me

**Comment by Palakkgoyal** [comment]
@AbhineshJha I have already asked to assign it to me

**Comment by AbhineshJha** [comment]
so what ??? I am also wanted to do..

**Comment by tamalCodes** [comment]
Hi @Palakkgoyal , you can start working on the issue, assigning it to you 🚀 
Please make sure that the navbar works just fine in ALL devices.
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by Palakkgoyal** [comment]
> Hi @Palakkgoyal , you can start working on the issue, assigning it to you 🚀 Please make sure that the navbar works just fine in ALL devices.
> 
> ## 📑 Checklist in case you missed something
> * [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
> * [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.
> 
> Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

Sure, I will take care of that
