### ISSUE TITLE
🐞Bug: Make Hero section responsive

### ISSUE THREAD

**Issue by Palakkgoyal** [MilanCommunity/Milan#1106]
### What would you like to share?

The hero section of Milan is not responsive and which doesn't look good on small devices which in turn degrade UX.
I want to work on this issue.
![Screenshot 2023-10-02 133845](https://github.com/MilanCommunity/Milan/assets/116902573/7484c2db-d18b-44e2-962e-6486b74934d5)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Palakkgoyal , can you please explain what do you mean by not responsive ?  To me on the first look, it looks really well.
![image](https://github.com/MilanCommunity/Milan/assets/72851613/d9401df7-c7ce-4fb2-ac21-bd0d9e4a4878)

**Comment by Palakkgoyal** [comment]
Sorry, for being a bit vague. I mean on some devices it is not behaving properly. For example: Galaxy Fold and Nest Hub
![Screenshot 2023-10-02 223909](https://github.com/MilanCommunity/Milan/assets/116902573/baa291bb-b1ee-43fb-a364-73cd2143e720)
![Screenshot 2023-10-02 223942](https://github.com/MilanCommunity/Milan/assets/116902573/53981876-9f3a-4dbc-b507-e082cf5a07ad)

**Comment by tamalCodes** [comment]
That sounds perfect. However, 

- I would like to put this issue on hold because #1083 is going on which takes care of the responsiveness.
- Since this is of very high priority, I'll wait for 3-4 days and if there is no response from them, I'll assign this issue to you.
- Also, please complete #1100 before taking on another issue. 

Thanks for the time and patience, I will hold this issue temporarily.

**Comment by Palakkgoyal** [comment]
> That sounds perfect. However,
> 
> * I would like to put this issue on hold because [🐞Bug: Website not responsive in some sections #1083](https://github.com/MilanCommunity/Milan/issues/1083) is going on which takes care of the responsiveness.
> * Since this is of very high priority, I'll wait for 3-4 days and if there is no response from them, I'll assign this issue to you.
> * Also, please complete [💡Feature: Make navbar scroll sensitive #1100](https://github.com/MilanCommunity/Milan/issues/1100) before taking on another issue.
> 
> Thanks for the time and patience, I will hold this issue temporarily.

Okay, I will wait for that and also send PR for [💡Feature: Make navbar scroll sensitive #1100] asap
