### ISSUE TITLE
🐞Bug: Signup button border increases on hover causing unusual effect

### ISSUE THREAD

**Issue by snehafarkya** [MilanCommunity/Milan#1108]
### Description

Hi @tamalCodes, I am Sneha Farkya from India. I am a front-end developer and technical writer. 

### Problem: 
I saw your website and loved the ideation but as soon as I hover the signup button, a border comes in which disturbs the navbar. This is because you have given a 1px border instead of 2px. See here: 

https://github.com/MilanCommunity/Milan/assets/63949465/0379056f-a796-442e-8265-2755de9fe0d4

### Solution
I can either make the button width 2px each or change the width to 1px on hover

https://github.com/MilanCommunity/Milan/assets/63949465/1d10c32c-d264-4180-a30d-294fbcbdfa64 

Assign this task to me under **hacktoberfest** and I would be happy to contribute. 
Thank you.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi there, this is being worked on in #1089 , so will be closing this for now as it is a duplicate.
