### ISSUE TITLE
🐞Bug: Organize content center so that spaces can be utilized in Sign In page

### ISSUE THREAD

**Issue by subrat611** [MilanCommunity/Milan#1118]
### Description

Organize content center so that spaces can be utilized.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/77252075/a7b10292-1a78-44d2-a5cd-9aa7b701d223)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Nwakaego-Ego** [comment]
Hi, Please assign this issue to me

**Comment by tamalCodes** [comment]
Hi @subrat611 , @Nwakaego-Ego  - we are currently looking for these changes in particular. So I will be closing this issue shortly. Thankyou so much for showing interest in contributing to this project.

Do check out our `Milan-Backend` repo AND/OR other issues.
Thanks.
