### ISSUE TITLE
Bug: Website responsiveness for all devices

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan#1119]
### Description

The website is breaking at certain points and angles, the responsiveness would be fixed.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by sahilrohera10** [comment]
Hey @tamalCodes , i will love to contribute in fixing UI issues, please assign this to me.
Thanks

**Comment by varundhand** [comment]
Hi @tamalCodes , I would love to contribute to this issue as well!

**Comment by tamalCodes** [comment]
Hi @varundhand , you can go ahead and remove all the circles that we have. We added those initially but i think we would be better without it.

**Comment by varundhand** [comment]
Yes @tamalCodes it would definitely look cleaner without them. I'll issue the PR today itself!

**Comment by sahilrohera10** [comment]
@tamalCodes , please assign some UI issues to me as well, i will love to contribute.
Thanks

**Comment by tamalCodes** [comment]
Hi @sahilrohera10 , i would love if you could fix the responsiveness for tablet devices.
![image](https://github.com/MilanCommunity/Milan/assets/72851613/50913163-a8fb-43a3-b73c-6c386d326da5)

**Comment by sahilrohera10** [comment]
@tamalCodes , Okie will love to do, please assign this to me

**Comment by varundhand** [comment]
Hey @tamalCodes , Im done with my code but as I was going through the code, I came across this beauty:

<img width="538" alt="Screenshot 2023-10-17 at 7 38 45 PM" src="https://github.com/MilanCommunity/Milan/assets/110025628/c4dc36b6-fec2-43d5-aaa1-5187fbffbe0b">

Should I comment this or maybe add TODO to it?

**Comment by tamalCodes** [comment]
> Hey @tamalCodes , Im done with my code but as I was going through the code, I came across this beauty:
> 
> <img alt="Screenshot 2023-10-17 at 7 38 45 PM" width="538" src="https://user-images.githubusercontent.com/110025628/275862512-c4dc36b6-fec2-43d5-aaa1-5187fbffbe0b.png">
> Should I comment this or maybe add TODO to it?

Just remove that 😂

**Comment by sahilrohera10** [comment]
@tamalCodes PR done with the responsiveness for tablet devices, please review it

**Comment by sahilrohera10** [comment]
![image](https://github.com/MilanCommunity/Milan/assets/90958499/3564db6f-7b38-4ea7-b955-9f98194763dd)


all checks are passing but still error why??

**Comment by varundhand** [comment]
@tamalCodes #1137 is ready for review

**Comment by sahilrohera10** [comment]
@tamalCodes , thanks for accepting my pull request, now please assign me more tasks, so that i can work more on it

**Comment by akash0708** [comment]
Hello @tamalCodes , the tablet view is still not responsive, I would like to work on it. Should I create another issue for it? Or link my PR to this issue?

**Comment by akash0708** [comment]
Hey @tamalCodes 
![Screenshot_2023-10-22-17-49-29-024_com android chrome](https://github.com/MilanCommunity/Milan/assets/110753356/84b30f13-cbdb-4b44-b3bf-a8fb18f3f264)

The website still looks like this on a tablet. I've good experience with both css and Next.js, I will get the work done quickly and efficiently.
