### ISSUE TITLE
🐞Bug: In Tablet Mode Spacing is between Login and signup is almost 0

### ISSUE THREAD

**Issue by Ayushpanditmoto** [MilanCommunity/Milan#1120]
### Description

https://github.com/MilanCommunity/Milan/assets/31253617/960b9b59-68b2-4ee5-a95a-627f4aed68a9

### Screenshots

![Screenshot_5](https://github.com/MilanCommunity/Milan/assets/31253617/fcdbf176-dfc3-4f2b-ae30-7c86c50f3f57)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Ayushpanditmoto** [comment]
okay please assign me

**Comment by tamalCodes** [comment]
This has already been fixed. I will deploy it soon.
