### ISSUE TITLE
🐞Bug: Contact us button redirecting to white screen

### ISSUE THREAD

**Issue by singodiyashubham87** [MilanCommunity/Milan#1126]
### Description

When I clicked on the Contact Us button in the footer it just redirected me to a black page with nothing in it.

### Proposed Solution

I'll debug what the problem is and will handle the click event properly so that the user will be able to contact the project owners.

Kindly assign me this issue under Hacktoberfest'23

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/93720428/ddb91841-4add-4636-8c48-548a67874e51)
![Screenshot from 2023-10-06 19-23-43](https://github.com/MilanCommunity/Milan/assets/93720428/2a3cab55-d2ce-41e3-94a3-f0be858c60e9)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @singodiyashubham87 , this is being currently done in #1082 where we are developing a custom modal.
