### ISSUE TITLE
Feature: Add custom previous and next buttons to image slider to past events section

### ISSUE THREAD

**Issue by singodiyashubham87** [MilanCommunity/Milan#1127]
### Description

There is no option in the past event section's sliding images to control the slide or to see the previous or next image.

Kindly assign me this issue under hacktoberfest'23

### Proposed Solution

I want to add two buttons on the rightmost and leftmost side of the image carousel to go for next and previous images.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/93720428/d7be6e6c-c5e3-4b57-b0ab-eb1422d06963)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @singodiyashubham87 , you can start to work on it !
Make sure that it is responsive across all devices. 


## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by TusharRastogi04** [comment]
hii @tamalCodes .please assign this issue to me as it seems a perfect fit for my first open source contribution

**Comment by tamalCodes** [comment]
> hii @tamalCodes .please assign this issue to me as it seems a perfect fit for my first open source contribution

Someone else is already working on it Tushar !

**Comment by singodiyashubham87** [comment]
@tamalCodes When I'm trying to setup the project locally then the clubs page is not showing any data, I've also setup the Milan-Backend too.
Can you please assist me?

![image](https://github.com/MilanCommunity/Milan/assets/93720428/c890207b-323b-4085-93d9-55c3bb094c43)

![image](https://github.com/MilanCommunity/Milan/assets/93720428/548393a5-c54b-4137-b121-4bcb7a069138)

**Comment by tamalCodes** [comment]
> @tamalCodes When I'm trying to setup the project locally then the clubs page is not showing any data, I've also setup the Milan-Backend too. Can you please assist me?
> 
> ![image](https://user-images.githubusercontent.com/93720428/273467490-c890207b-323b-4085-93d9-55c3bb094c43.png)
> 
> ![image](https://user-images.githubusercontent.com/93720428/273467516-548393a5-c54b-4137-b121-4bcb7a069138.png)

Have you configured the `.env` file for the Frontend ?

**Comment by singodiyashubham87** [comment]
@tamalCodes I'm not using Razorpay and geolocation api so I put random strings in them, have a look -

![image](https://github.com/MilanCommunity/Milan/assets/93720428/196853af-5799-4e88-80ce-da240f8b6d80)

**Comment by tamalCodes** [comment]
Well i  can see that you are using `http://localhost:5000` correctly - the API should work correctly, is there any error in the console ? If there is, maybe try resolving that.

**Comment by singodiyashubham87** [comment]
@tamalCodes I'm getting Internel Server Error(500) for the clubs page, No idea why.
![image](https://github.com/MilanCommunity/Milan/assets/93720428/be52691b-2c59-4dc9-be31-a3678718817f)

**Comment by tamalCodes** [comment]
That's cool, my best guess is since you are on a new DB you are not getting any data. As the DB is empty. You can paste http://localhost:5000/clubs in the browser and see the result.

 - You can perhaps sign up as a club with random details. (Not google auth)
 - Then the profile page appears, you can make your changes and simply push the code for the FE.

**Comment by singodiyashubham87** [comment]
@tamalCodes Not able to sign in, it buffers then stops

**Comment by tamalCodes** [comment]
If there are any errors please paste it here. The errors can be seen in the server's terminal and Browser's console.
Make sure that the DB is set up properly and also let me know what appears in the networks tab when you are trying to sign Up.

**Comment by tamalCodes** [comment]
# Let's catch up 🙋🏻‍♂️
Hi there, it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at milanhub.org@gmail.com

**Comment by singodiyashubham87** [comment]
@tamalCodes Hey Tamal I tried my best to setup the environment on my local computer but was not able to get it done even after doing the changes you suggested, I guess you should open this issue to anyone willing to work.
