### ISSUE TITLE
Docs: Contributors are not listed in read.md

### ISSUE THREAD

**Issue by mohitd404** [MilanCommunity/Milan#1128]
### Description

Contributors are not listed in the read.md file ! 

### Screenshots

![2](https://github.com/MilanCommunity/Milan/assets/146939900/95467ea7-5507-46f5-92aa-a9edb84b322d)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by mohitd404** [comment]
@tamalCodes Please assign this issue to me !! I would love to contribute in this issue! Thank you !

**Comment by tamalCodes** [comment]
Hi @mohitd404 , i have 150 contributors, imagine seeing that many images in the readme. That's why we have removed that feature, the contributors can already be seen in the right side panel.

![image](https://github.com/MilanCommunity/Milan/assets/72851613/b9de4244-1f83-4c5b-a742-cb7af366c6bc)
