### ISSUE TITLE
Docs: Adding more shield badges in readme

### ISSUE THREAD

**Issue by mohitd404** [MilanCommunity/Milan#1129]
### Description

These badges provide quick visual information about the status or health of a project, such as its build status, code coverage, license, version, or other relevant metrics. They serve several purposes:

### Screenshots

Example 1)

![shie b](https://github.com/MilanCommunity/Milan/assets/146939900/a03f1eea-dabe-4a44-8c5c-5cb2ede05681)

Example 2)

![shield badges](https://github.com/MilanCommunity/Milan/assets/146939900/d51353ec-b0c9-4e4b-8d73-2f9ce1ea118e)
[Hacksquad2023 (2).txt](https://github.com/MilanCommunity/Milan/files/12839829/Hacksquad2023.2.txt)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by mohitd404** [comment]
@tamalCodes please assign this issue to me !

**Comment by tamalCodes** [comment]
Hi @mohitd404 , we already have the License, release, and repo size  - so we are not looking forward to adding more badges to the readme as of now.
