### ISSUE TITLE
Scroll Top Button Does Not Work Well With Scroll Height

### ISSUE THREAD

**Issue by BowaDAO** [milancommunity/Milan#1130]
The ScrollTop button on the homepage should sync perfectly well with a user's scroll height,but at the moment it does not hence breaking its behavior. I would love to solve this if you can assign it to me.

**Comment by zetabug** [comment]
@tamalCodes i would love to work on this issue. You can assign this to me.

**Comment by umerhere** [comment]
@tamalCodes I want to work on it. Please assign this to me

**Comment by dev0869** [comment]
Hey I would love to work on this issue.
