### ISSUE TITLE
Bug: contact us button is broken in footer

### ISSUE THREAD

**Issue by MahendraDani** [MilanCommunity/Milan#1131]
### Description

- When the `contact us` button in footer is clicked the website becomes blank. The button neither redirects to any page nor shows any contact form. It seems like the website hangs out and user needs to refresh to see the website live again. 

- Steps to Reproduce
1. Go to https://milanhub.org/
2. Scroll down to footer of the website
3. Click on `contact us` button

- Screen recording

https://github.com/MilanCommunity/Milan/assets/116940083/a663ff8d-6a8c-453d-a30b-083a8a70062b

## Solution 1
We can show Work in progress as shown in https://milanhub.org/shop 

## Solution 2
We can develop a contact us page and create a contact form which will open when `contact us` button is clicked.

### Screenshots

Screen shot for proposed solution 1
![milan_contact](https://github.com/MilanCommunity/Milan/assets/116940083/50ae681d-3ced-48f7-b8d4-138b75d3a6a5)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by VishalMyla** [comment]
please assign this issue to me

**Comment by MahendraDani** [comment]
@VishalMyla 
I will be working on this issue.
Please checkout other open issues.
Thanks!

**Comment by tamalCodes** [comment]
This is being worked on in #1082 , if they are inactive for a few more days I'll assign it to you. Until then please stay on hold.

**Comment by MahendraDani** [comment]
> This is being worked on in #1082 , if they are inactive for a few more days I'll assign it to you. Until then please stay on hold. Do not make PR for the same for now.

@tamalCodes alright

**Comment by MahendraDani** [comment]
@tamalCodes Should I start working on this issue now!

**Comment by tamalCodes** [comment]
Sure go ahead, please take a look at [this issue](https://github.com/MilanCommunity/Milan/issues/1082) to have a more understanding of what we desire to have. In case of more doubts please let me know !

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by MahendraDani** [comment]
@tamalCodes Thanks.
Would you please tell me which input fields should be there fir users in the form when the modal opens after the button is clicked.
For example - 
`name`,`email`,`query` , etc?

**Comment by tamalCodes** [comment]
I am planning to use the [Report schema](https://github.com/MilanCommunity/Milan-Backend/blob/main/schema/user/ReportProblemSchema.js) for the same, so the details can be the same as what we have in the schema, and API call would also be needed, one might be already present in the Frontend code.

In the backend, we have the [Report route](https://github.com/MilanCommunity/Milan-Backend/blob/f25b1e9fd543f7705737ca6059a84f3999c06d8b/routes/user/User.js#L57) which can be used.

**Comment by MahendraDani** [comment]
Understood.
So I need to develop the UI of contact us form and then connect it to report route in the backend right?

**Comment by MahendraDani** [comment]
> > @tamalCodes So I need to develop the UI of contact us form and then connect it to report route in the backend right?
> 
> yes the submit button will just send over that data.  You can use this already coded [function](https://github.com/MilanCommunity/Milan/blob/fc2a1911c50c2771c85f006b1c41e06918f7597f/src/service/MilanApi.js#L45) too for the same.
> 

Alright!
I will try to complete this asap.
