### ISSUE TITLE
Feature: We can have a better smooth scrolling effect

### ISSUE THREAD

**Issue by sahilrohera10** [milancommunity/Milan#1133]
### Description

When someone clicks on the "go to top" button on the main page, it is going directly on the top of the page, so here we can have some smooth scrolling effect on going to the top of the page, which enhances the user experience.

### Proposed Solution

Well ! 
This can be done using few lines of CSS of scrolling.
I will love to contribute, if you assign this to me.
Thanks

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
I don't understand what you are trying to say what do you mean by "smooth scrolling" ?
