### ISSUE TITLE
Suggestion: Button Hover Effect

### ISSUE THREAD

**Issue by dhananjay-Byte** [milancommunity/Milan#1134]
### Description

I observed that hover effect of buttons especially that are side by side is not differentiative. I believe that the effect should be somewhat unique from the basic implementation to give user a better understanding that this button will navigate me to other page.

### Proposed Solution

Current Implementation:
![Milan _ Home - Google Chrome 2023-10-16 19-25-11](https://github.com/MilanCommunity/Milan/assets/82323909/400925ce-1836-4796-9983-d27fdb6134db)

My Suggestion:
![Milan _ Home - Google Chrome 2023-10-16 19-28-09](https://github.com/MilanCommunity/Milan/assets/82323909/1b875c29-6ebf-471f-aa3c-1da23216e25f)

I decided to go with the heading color for effect but you can give your suggestion.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by ezhillragesh** [comment]
Hello @dhananjay-Byte Can you assign this issue to me. I would Like to work on this.

**Comment by tamalCodes** [comment]
Hi @dhananjay-Byte that would be a nice addition in terms of UI/UX. Please go ahead.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by priyachowdary1978** [comment]
Hello @dhananjay-Byte  Can you assign this issue to me. I would Like to work on this.

**Comment by tamalCodes** [comment]
Hi @dhananjay-Byte , why are there 2 different PRs for a single issue ?
Can you please close either one ?
