### ISSUE TITLE
Bug: Number Circle missing before "Collaborate" Heading

### ISSUE THREAD

**Issue by varundhand** [MilanCommunity/Milan#1135]
### Description

Currently, the website's sections include "Collaborate," "Connect," and "Build." 
And, there is a **number circle** before each one of them, **except for "Collaborate"** . This **inconsistency** can be improved for a more cohesive design.

### Proposed Solution

To maintain design **consistency** across sections, we propose adding a number circle element before the **"Collaborate"** heading. This will enhance the **visual appeal and user experience.**

### Screenshots

_The Collaborate section does not have number circle:_

![Screenshot 2023-10-16 at 10 16 06 PM](https://github.com/MilanCommunity/Milan/assets/110025628/aafc6aa1-2062-437b-a3b7-0987654f506d)

_Rest of the sections have that:_

![Screenshot 2023-10-16 at 10 17 47 PM](https://github.com/MilanCommunity/Milan/assets/110025628/61947b48-0ee7-4c3d-af12-3bb13614dd08)

![Screenshot 2023-10-16 at 10 17 53 PM](https://github.com/MilanCommunity/Milan/assets/110025628/f3600f31-e60b-453e-9d4e-392e6b1d63a9)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by sahilrohera10** [comment]
Heyy @tamalCodes , I will love to solve this bug, this only needs a number inside the circle with the same css as the other sections are having, can you please assign this issue to me? I will love to contribute.

**Comment by tamalCodes** [comment]
Hi thanks for raising this issue however we would like to fix a lot of design flaws in total. We have the work ongoing in #1119 would you like to collaborate in that ?

**Comment by sahilrohera10** [comment]
Yes, i will love to contribute, and there i can fix the major ui flaws, right?

**Comment by harsh31dangi** [comment]
Hi @tamalCodes , can I work on this issue?

**Comment by tamalCodes** [comment]
Hi , @sahilrohera10 @harsh31dangi ping up there in the issue.

@varundhand , you can just copy-paste what you want to remove (whatever you mentioned here) in that issue itself. and we can proceed further. That issue has a https://github.com/MilanCommunity/Milan/labels/multi-asignees tag, meaning more than 1 person can collaborate and make PRs for the same issue.

To avoid confusion I'll close this issue and let's continue there !

**Comment by varundhand** [comment]
Sure thing @tamalCodes!
