### ISSUE TITLE
Bug: irrelevant text in console

### ISSUE THREAD

**Issue by MahendraDani** [MilanCommunity/Milan#1141]
### Description

- Irrelevant text is shown in console at all times.

## How to reproduce
1. Go to [Milanhub](https://milanhub.org/)
2. Right click on the screen and then click on `inspect`
3. Go to `console`
4. You will see the text in console : `WTF is wrong bro`

### Proposed Solution

- The text should be removed from the console.
- The bug lies in the Milan-main\src\components\Banners\Milaninfobanner.jsx

### Screenshots

https://github.com/MilanCommunity/Milan/assets/116940083/9ab406de-fd90-4359-abad-9d2b743d0b97

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Virtual4087** [comment]
Hi i would love to work on this

**Comment by MahendraDani** [comment]
@Virtual4087 
I would be working on this issue. Please find other open issues to work on.
Thanks!

**Comment by MahendraDani** [comment]
@Virtual4087 
Please close your pull request. You had not been assigned.
In opensource we follow strict rules, you should at least wait until the maintainers assign you the issue before making a pull request.

cc @tamalCodes

**Comment by tamalCodes** [comment]
@MahendraDani please include the changes of this issue in your latest PR of yours which is #1140

**Comment by MahendraDani** [comment]
Yes, I will
