### ISSUE TITLE
Feature: Enhance Website Design for a More Professional and Balanced Look

### ISSUE THREAD

**Issue by varundhand** [MilanCommunity/Milan#1144]
### Description

I'd like to propose a few design enhancements for our website to create a more **professional** and **balanced** appearance.The goal is to make the website more **visually appealing** and **user-friendly.**

### Proposed Solution

- In the second of the website ,titled "**Connect**," I have applied changes to improve the **visual appeal** and **balance** of the section.
- **Specifically, I have swapped the image position to the right side of the text to create a more visually appealing and balanced layout.**

### Screenshots

_Before:_

https://github.com/MilanCommunity/Milan/assets/110025628/9b071972-6e81-48ea-9583-6858a026c59e

_After:_

https://github.com/MilanCommunity/Milan/assets/110025628/3dd25807-d7f4-44d9-ac5b-d8f783224c52

These changes aim to improve the overall user experience and make the website more inviting to visitors.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by varundhand** [comment]
@tamalCodes please assign this issue to me. Thanks! :)

**Comment by zetabug** [comment]
Hey @varundhand @tamalCodes , I am confident that I can do this UI change. It's really simple, and multiple ways to do it:
1. We can set the flex direction of the parent container as row reverse
2. Or we can just arrange those elements in the html/jsx code itself.

please assign me this issue.

**Comment by tamalCodes** [comment]
Hi there sorry for being late, was not well at all. See for now I would not recommend making any design change as we will be refactoring the whole design soon. I have sole major UI changes planning and will launch it up soon.

Till then I'll be closing this, will re-open if needed.

**Comment by varundhand** [comment]
Sure thing @tamalCodes . I'll be happy to incorporate UI changes as well! You can ping me up anytime
