### ISSUE TITLE
Docs: Add link Conventional Pull Request

### ISSUE THREAD

**Issue by akash0708** [MilanCommunity/Milan#1145]
### Description

A lot of people new to open source might not know what a conventional PR is. Hence adding a link to the official GitHub documentation of Conventional PR will help newcomers. 

### Screenshots

This is what it looks like now:

![image](https://github.com/MilanCommunity/Milan/assets/110753356/ba4047b1-37d6-4561-9d5c-7bf2f71574a8)

I want to add a clickable link to it leading to [this](https://github.com/marketplace/actions/conventional-pull-request) website

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Great issue @akash0708 , i would recommend something else for the same. We have some description of the Pull request mentioned [here](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#pull-request-title-format-), how about linking that `use conventional pull requests` to this section of the website.

**Comment by akash0708** [comment]
Sure, I'll do this right away!
