### ISSUE TITLE
Bug: footer has some styling issues as well as text wrapping

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [milancommunity/Milan#1148]
### Issue Summary:
The footer of the Milan NGO and Charity collaboration website exhibits several visual and styling issues that need attention for an improved user experience. Specifically, two key issues have been identified:

#### 1. Text Wrapping Problem:

 Description: The text in the footer section is not displayed appropriately, leading to an unattractive and disorganized appearance. This affects the overall aesthetics of the website.
 Expected Behavior: The text should be formatted and aligned properly to ensure readability and a visually pleasing look.
 Steps to Reproduce:
- > Visit the Milan NGO and Charity collaboration website.
- > Scroll to the bottom of the page to access the footer section.
- > Observe the way text is wrapped and presented in the footer.

#### 2. Lack of Emphasis in Headings:

Description: The headings in the footer section do not stand out and lack emphasis. They appear to be visually similar to the rest of the content, which can make it challenging for users to quickly identify the different sections.
Expected Behavior: Headings in the footer should be styled in a way that sets them apart from regular text, ensuring that they are easily distinguishable.

 Steps to Reproduce:
- > Visit the Milan NGO and Charity collaboration website.
- > Scroll to the bottom of the page to access the footer section.
- > Observe the styling and emphasis (or lack thereof) in the headings.

### Suggested Solution:

For the text wrapping issue, consider adjusting the CSS styles for the footer text to ensure proper alignment and readability.

To address the lack of heading emphasis, update the CSS styles for the headings in the footer, such as using larger fonts, bold text, or distinctive colors.

### Screenshots

Footer issue:

<details>
<summary>Footer issue screenshot</summary>

![image](https://github.com/MilanCommunity/Milan/assets/47966497/488865b3-7608-4e24-ae50-bfa495b98cc1)

</details>

Improved version: 

<details>
<summary>Improved version screenshot</summary>

![image](https://github.com/MilanCommunity/Milan/assets/47966497/1817b715-7ee9-4f24-9a2c-daf52a499572)

</details>

### Browser 🥦

Google Chrome, Opera, Edge

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Shivangbhatnagar237** [comment]
I need to discuss on the 'emphasis' part of this issue, is that required?
I can just solve the text-wrapping issue. Any other issues that I must combine? Any suggestions?

**Comment by devAlisha** [comment]
Can you assign this issue to me?

**Comment by dev0869** [comment]
Hey I would love to work on this issue.
