### ISSUE TITLE
Feature: Install tailwind css

### ISSUE THREAD

**Issue by akash0708** [MilanCommunity/Milan#1149]
### Description

Upgrade the styling of the website with tailwind css

### Proposed Solution

Current website uses vanilla css for styling, using Tailwind css will reduce code duplication and help in increasing consistency.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by RajuGangitla** [comment]
@akash0708 converting whole css code to tailwind css ? It takes more time

**Comment by Lokendrakushwah12** [comment]
hello @akash0708 I can install the Tailwind CSS so further from here people can use tailwind instead of raw CSS
you can assign this issue to me

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by tamalCodes** [comment]
A great issue this is, however, this would take a lot of time so I think we can go step by step. Let me close this issue real quick for now and first [discuss](https://github.com/orgs/MilanCommunity/discussions/1153) how we are thinking to proceed.
