### ISSUE TITLE
Bug: typo in home screen

### ISSUE THREAD

**Issue by Lokendrakushwah12** [MilanCommunity/Milan#1150]
### Description

the spelling of tomorrow is wrong here

### Proposed Solution

it should be tomorrow

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/118094744/246a1592-fc5e-404a-9db1-b84ad028729f)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Roshanchau** [comment]
can you assign me this issue?

**Comment by tamalCodes** [comment]
Go ahead @Lokendrakushwah12 , do raise a PR !

**Comment by Lokendrakushwah12** [comment]
Please check out the PR #1158
