### ISSUE TITLE
Docs: Add a link that leads to the official docker desktop download center

### ISSUE THREAD

**Issue by akash0708** [MilanCommunity/Milan#1151]
### Description

Convert this plain text to a link that leads to the official docker docs for downloading [docker desktop.](https://docs.docker.com/get-docker/)

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/110753356/a46ada43-629f-4b74-9de0-a0d3016bd1c9)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tejas-raskar** [comment]
I would like to work on this

**Comment by tamalCodes** [comment]
Great spot @akash0708 , go ahead. Make sure that you make a proper PR !
