### ISSUE TITLE
📂Other: wrong alignment 

### ISSUE THREAD

**Issue by Lokendrakushwah12** [MilanCommunity/Milan#1159]
## Description
the width of paragraph text is smaller compare to the width of images

## Screenshot 
![image](https://github.com/MilanCommunity/Milan/assets/118094744/f12dce08-0763-4b14-8f82-1f3c93995e87)

Need to fix this 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Raj100679** [comment]
Hello @tamalCodes @Lokendrakushwah12 , Can you assign this issue to me?

**Comment by tamalCodes** [comment]
Hi @Lokendrakushwah12 , we are working  on re-designing this section so I will be closing this issue for now.
