### ISSUE TITLE
Bug: the shop portal and user profile are missing the footer 

### ISSUE THREAD

**Issue by Yash-Sajwan24** [MilanCommunity/Milan#1160]
### Description

The shop portal and User profile do not have a footer.

### Proposed Solution

I would like to add the footer to both of these links.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/52412969/83d2c8b8-71ae-4118-a709-628f484cdecd)

![image](https://github.com/MilanCommunity/Milan/assets/52412969/d460eb12-bfff-44b3-bac2-1ecea6ba904a)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by YashM211** [comment]
Could you assign me this issue

**Comment by swapnilbhakare** [comment]
@TahaHameed23 I would love to work on this issue

**Comment by tamalCodes** [comment]
Hey @Yash-Sajwan24 , you can start to work on this. But we would have the Footers only on pages that do not have a Coming Soon.

**Comment by Yash-Sajwan24** [comment]
@tamalCodes I have submitted a pull request for your review. Please take a look at it. https://github.com/MilanCommunity/Milan/pull/1169
