### ISSUE TITLE
Bug: The home page is not responsive between width (500px - 100px)

### ISSUE THREAD

**Issue by Yash-Sajwan24** [MilanCommunity/Milan#1161]
### Description

The home page is not responsive between width (500px - 1000px). The image size is fixed due to which the description tends to acquire less space.

### Proposed Solution

I would like to make it responsive.

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/52412969/3889842a-44a2-499a-8889-9821fffb86af)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Raj100679** [comment]
Hello @tamalCodes , Can you assign this issue to me

**Comment by Lokendrakushwah12** [comment]
Please check issue #1159 it's similar to this issue
