### ISSUE TITLE
Docs: Typo in `CloneSetup.md` from repo to repository

### ISSUE THREAD

**Issue by Yash-Sajwan24** [MilanCommunity/Milan#1162]
### Description

Typo in CloneSetup.md file:

I would change : 

```repo ``` -> ```repository```

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/52412969/16bc9364-7429-48cb-bebb-10fd270c81fe)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by YashM211** [comment]
Can you assign this issue to me

**Comment by tamalCodes** [comment]
Hi @Yash-Sajwan24 , you can start to work on this

**Comment by Yash-Sajwan24** [comment]
I have addressed and submitted the pull request. @tamalCodes Please look at it whenever you can using the following link: https://github.com/MilanCommunity/Milan/pull/1167.
