### ISSUE TITLE
Other: Sign in Sign up buttons in Navbar

### ISSUE THREAD

**Issue by Saekit** [milancommunity/Milan#1166]
### What would you like to share?

I would like to propose some style changes to the Sign in/Sign up buttons in the navbar. 
1. Change "Sign in" to "Log in" for better UI/UX experience, also to match the footer
2. Change the style of the Log in button to only have an underline (on hover), so it differentiates from the Sign up button
3. Align all nav items

#### Issues:

Funny looking button behavior:

https://github.com/MilanCommunity/Milan/assets/42038008/6ced48af-4d12-4ce3-9015-5328961447aa

Misalignment: 
<img width="1004" alt="Screenshot 2023-11-02 at 1 22 10 PM" src="https://github.com/MilanCommunity/Milan/assets/42038008/572ae755-caa5-41ab-9498-6ca63ef6eb66">

#### Solution:
<img width="864" alt="Screenshot 2023-11-02 at 1 15 44 PM" src="https://github.com/MilanCommunity/Milan/assets/42038008/4bb1e913-08dc-4610-b104-0210ce5aaaa5">

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Sounds good to me however, I would also like to suggest some changes too.

 - The buttons can be changed, instead of having two, we can have one.
 - We just keep a main button, which says `Sign In` or something like that (check the screenshot below)
 - Also the line height probably is probably causing some issues with the misalignment.


![image](https://github.com/MilanCommunity/Milan/assets/72851613/f3a36ad6-ba99-474b-9665-83f8e2c8be9b)

**Comment by Saekit** [comment]
@tamalCodes Just to clarify, are you suggesting completely removing the Sign up button from the navbar and only having a log in button that keeps the current style?

**Comment by deveshtanwar-IMG** [comment]
sir can you please assign this issue to me ?

**Comment by RajMhatre20** [comment]
Can i work on this?

**Comment by tamalCodes** [comment]
> @tamalCodes Just to clarify, are you suggesting completely removing the Sign up button from the navbar and only having a log in button that keeps the current style?

Yes

**Comment by Bilal7659** [comment]
can i work on it as it available i know it

**Comment by Saikat-Mandal** [comment]
Hi there @tamalCodes i went through the conversation above. I guess i can the fix this issue.

**Comment by prajwalbandak** [comment]
Hey @tamalCodes , Made the changes in the local, Can i make PR request?

**Comment by dev0869** [comment]
Hey I would love to work on this issue.
