### ISSUE TITLE
Bug: Button alignment issue in mobile responsive

### ISSUE THREAD

**Issue by subrat611** [MilanCommunity/Milan#1170]
### Description

The buttons **Donate** and **Read more** are not aligned properly.

### Proposed Solution

Read more button margin 0.
align-items need to center.

### Screenshots

Issue:
![image](https://github.com/MilanCommunity/Milan/assets/77252075/bba52e2a-4775-4ac0-9978-8ef2cdc0479a)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Raj100679** [comment]
Hello @tamalCodes , Can you assign this issue to me?

**Comment by Raj100679** [comment]
Hello @tamalCodes , Can you assign this issue to me?

**Comment by Emm-dev0** [comment]
Can u pls assign this issue to me I would like to work on it

**Comment by RajMhatre20** [comment]
Can i work on this?

**Comment by TahaHameed23** [comment]
Hey @subrat611, this issue has already been fixed. Here is the PR: https://github.com/MilanCommunity/Milan/pull/1122#issue-1928756400
I checked and didn't find this issue at screen width 320px. Can you tell at what screen size you experienced this?

**Comment by subrat611** [comment]
![image](https://github.com/MilanCommunity/Milan/assets/77252075/495ed67b-efb9-4e9c-996b-7cd669af633b)
Thanks for informing me. And yes the bug has been fixed.
