### ISSUE TITLE
Bug: Validation error in signup form  

### ISSUE THREAD

**Issue by deepakk33** [MilanCommunity/Milan#1172]
### Description

Validation error should come inside form only rather than in form Toast massage , it will help user to catch error easily.

### Proposed Solution

rather than using toast make object for every feild-state that can contains validation error as well so we can show error just below of the fields.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by Bashamega** [comment]
Hello:)
I am interested in solving this issue.
Can you assign me?

**Comment by tamalCodes** [comment]
Hi @Bashamega , you can go forward with the issue. 

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by Bashamega** [comment]
> Hi @Bashamega , you can go forward with the issue.
> 
> ## 📑 Checklist in case you missed something
> * [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
> * [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.
> 
> Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

Thank you very much

**Comment by Endless8** [comment]
Hey, I am willing to work on this issue
