### ISSUE TITLE
Bug: Broken UI in user page

### ISSUE THREAD

**Issue by devAlisha** [milancommunity/Milan#1175]
### Description

When resizing the screen on the User page, the carousel images for Events Attending overlap, leading to a visual issue that negatively impacts the user experience. This issue requires attention and resolution.

### Steps to Reproduce
1. Visit the User page by navigating to `/User/:userId`.
2. Ensure the initial screen size is set to 1440px.
3. Gradually reduce the screen size to a smaller resolution.
4. Observe the carousel images and note the overlap.

### Proposed Solution

Using window.innerWidth in combination with the resize event listener and React state

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/134960860/a8fc41e0-6159-443f-b532-d83679ee5225)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by devAlisha** [comment]
I'm willing to work on this issue
Please assign this to me

**Comment by chinmayborade** [comment]
I am interested to work on this

**Comment by tamalCodes** [comment]
Hi @devAlisha , as you said about the overlapping part, how about we do a slider because if you look at [this](https://github.com/MilanCommunity/Milan/blob/7b1b5e5159a9a99d0f23969855259390a49e8407/src/pages/Club/Profile/ClubProfile.jsx#L153) line here, you will notice that the data is just fixed which also causes responsiveness issue sometimes. 

A club might also do 10-15 events, so I assume a slider would be better.
If you look  at the [mentor's section](https://s2.hack4bengal.tech/), this would be a great example of what i want !

**Comment by devAlisha** [comment]
In the code we are already using a slider just like the [mentor section](https://s2.hack4bengal.tech/) 
when the screen size is <1200 then it is supposed to just show 1 card in that swiper but that is not working because we should use useEffect and useState along with event listener
Furthur, to improve the performance we can use window.matchMedia as it provides better performance
Please, share your views on this

**Comment by devAlisha** [comment]
There is a better, easier solution 
swiper library that we are using also provides the breakpoints attribute
![image](https://github.com/MilanCommunity/Milan/assets/134960860/0e0f298a-71dd-41e8-855d-32372a4eb7ae)
We can simply use this in both the pages (userProfile and clubProfile)
Should I implement this @tamalCodes ?

**Comment by devAlisha** [comment]
I've raised the PR please do review @tamalCodes 
Also, I've added pagination attribute from the swiper library because at the first glance it looked like event were cards instead of a slider

**Comment by Salonijain2210** [comment]
Please allow me the opportunity to resolve this issue at hand
