### ISSUE TITLE
Bug: The footer stays in the middle if the content is small

### ISSUE THREAD

**Issue by Avas77** [milancommunity/Milan#1183]
### Description

In the Clubs page, the footer stays in the middle of the page due to the content of the page being small resulting in a white blank space at the bottom. This does not look good in the UI as the footer should always stay at the bottom of the page.

### Proposed Solution

The container should have a min-height property and the display property should be set to flex which solves the issue 

### Screenshots

<img width="1680" alt="Screenshot 2023-12-20 at 16 40 17" src="https://github.com/milancommunity/Milan/assets/43259881/3bfe5315-7726-4c69-a997-6aef14122457">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Avas77** [comment]
I'm willing to work on this issue. Please assign this to me

**Comment by notajax24** [comment]
Can i work on this?

**Comment by dev0869** [comment]
Hey I would love to work on this issue.
