### ISSUE TITLE
Feature: Animation on login page & Sign Up Page

### ISSUE THREAD

**Issue by BroLetsCodeIt** [milancommunity/Milan#1188]
### Description

when we hover on the image of login page and sign up page . There should be a animation on hovering the image.

![image](https://github.com/milancommunity/Milan/assets/113767803/23be0e76-dd9e-42f9-8998-f7a72481fb6d)

for reference : check out this website : https://broletscodeit.github.io/Equilibrium_Website_Clone/

In the above website i have used some animations. so that one can get what kind of animation i am talking.

## Solution

we can you use various javascript libraries  like : 
- gsap 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This animations looks really good, does it have any impact on performance any how ?

**Comment by BroLetsCodeIt** [comment]
> This animations looks really good, does it have any impact on performance any how ?
If we use it only for one image then it is fine , but if we use animation for multiple images then it has impact on performance.

**Comment by tamalCodes** [comment]
I see, well i'd close the issue for now. The page looks good I belive, let me come up with any creative design 👁️👁️
