### ISSUE TITLE
Bug Report: Password Hide Option Not Functioning in Sign In

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [milancommunity/Milan#1192]
### Description

This bug report addresses an issue where the "hide password" functionality is not working as intended. Users are unable to hide the password, which impacts the user experience negatively. This bug needs to be resolved promptly to ensure the proper functioning of the password hide option.
 this issue creates problem  not in sign in but also in Sign up Page TOO

Assigm me this under JWOC'24
### Proposed Solution

debugging and fixing the js and HTMl markup fix the issue 

### Screenshots

![Screenshot from 2024-01-11 02-12-54](https://github.com/milancommunity/Milan/assets/44281971/b51afd64-62a7-4da1-a793-b312f1a757ae)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Himanxu1** [comment]
It's working perfectly fine @NaveenChandraAdhikari

**Comment by tamalCodes** [comment]
Same here, works fine for me too.

**Comment by NaveenChandraAdhikari** [comment]
Apology: Issue Only Occurs on My Machine @tamalCodes   but can I add Add Typewriter Effect to banner_header1 and Underlined Text in Footer auth_text for better UI

**Comment by tamalCodes** [comment]
Typewriter effects are generally considered bad UI both in terms of accessibility and SEO. I'll let that pass for now, i will be closing this issue.
