### ISSUE TITLE
Feature: Frontend Form validation required in Sign/Sign Up

### ISSUE THREAD

**Issue by Himanxu1** [milancommunity/Milan#1194]
### Description

Validation is crucial when it comes to form , Sign In and Sign Up pages should have validations 

### Proposed Solution

We can use Yup/Formik to make it work .

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by shashank20-02** [comment]
Please assign this task to me. I would love to work on this.

**Comment by tamalCodes** [comment]
Hi there, you have not checked out the code or the auth pages. We have custom hooks that take care of these. Would using a third-party library complicate this or ease this ?

![image](https://github.com/milancommunity/Milan/assets/72851613/b5f3b47c-3ab3-4b1d-8770-2865902827e3)

**Comment by vinaybhamre** [comment]
we can use zod + react-hook-form to implement the form

**Comment by tamalCodes** [comment]
> we can use zod + react-hook-form to implement the form

Currently, we are using the [useValidation hook](https://github.com/milancommunity/Milan/blob/main/src/hooks/useValidation.js) for this simple form. I think we will be using `zod + react-hook-form` soon when we set up how to generate events, funding, and more detailed and complicated stuff like that !

For now I will be closing the issue as for a form of this scale - we won't need extra codes.
