### ISSUE TITLE
Feature: Revamping the Navbar

### ISSUE THREAD

**Issue by tamalCodes** [milancommunity/Milan#1195]
### Description

We will be working on revamping the navbar for the desktop implementing a clean and minimal look with just one call to action in focus.

### Proposed Solution

I have made a basic [Figma prototype](https://www.figma.com/file/hVTYFuycHSgxTXmNRYOpGp/Untitled?type=design&node-id=0%3A1&mode=design&t=yvVrnpcWD5Wvb0Fx-1) which can be used for the same. The mobile view would be similar to what we have as of now. The colors and assets can be copied/exported from the design itself.

> [!IMPORTANT]  
> Make sure you make the PR to the `beta` branch, not `main`

### Screenshots

![image](https://github.com/milancommunity/Milan/assets/72851613/1c8204dd-0b70-4a3f-b187-eef49f6e3147)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by Himanxu1** [comment]
Hey would like to grab this one

**Comment by pranay911** [comment]
Heyy I like to worked on this

**Comment by tamalCodes** [comment]
Hi @Himanxu1 , would you be willing to work on this or should I assign to someone else ?

**Comment by ArshiyaArora** [comment]
hi @tamalCodes please assign me this issue under JWOC

**Comment by akash02ab** [comment]
hi @tamalCodes Please! Assign the issue to me, I am more than happy to contribute.

**Comment by gayathrik23** [comment]
hey @tamalCodes could you please assign me this issue. i like to contribute

**Comment by Hrx4** [comment]
Want to work on this issue under JWOC. Please assign it to me

**Comment by tamalCodes** [comment]
Looks like @Himanxu1 is busy - @Sneha-Sonkar you can start if you are available (reply if yes).
Would like to get this done ASAP. Also let us know if you are a part of any OSS event.

**Comment by harshkumrawat** [comment]
Hey would like to work on these issue.Please assign it to me

**Comment by Sneha-Sonkar** [comment]
> Looks like @Himanxu1 is busy - @Sneha-Sonkar you can start if you are available (reply if yes). Would like to get this done ASAP. Also let us know if you are a part of any OSS event.

@tamalCodes I am so sorry for replying this late, can i still take up this issue. I would love to work on it under JWOC. Yes, I am working on an issue but not in this project

**Comment by tamalCodes** [comment]
Cool, you can start to build it then - would love to have it done in quickly if possible !

**Comment by harshkumrawat** [comment]
Hey @tamalCodes  i have completed these point

**Comment by Sneha-Sonkar** [comment]
@tamalCodes thanks a lot for giving me the opportunity to work on this project. Actually, due to some personal issues, I couldn't work on it the way I could have and I already took a lot of your time. I am immensely grateful to you for being so patient and considerate.

**Comment by pranay911** [comment]
@tamalCodes Can u please assign this issue to me ?

**Comment by tamalCodes** [comment]
Sure @pranay911 , go ahead .

**Comment by pranay911** [comment]
Hey, @tamalCodes I would like to know the which color code used for the navigation item.

**Comment by pranay911** [comment]
![image](https://github.com/milancommunity/Milan/assets/65008142/5a6bdc5f-c7f0-4c8a-8078-b928c09dd92d)
Hey @tamalCodes I make some changes, please have a look

**Comment by tamalCodes** [comment]
Hi @pranay911 please make a Pull request following the guidelines

**Comment by pranay911** [comment]
> Hi @pranay911 please make a Pull request following the guidelines

Done

**Comment by FazeenIjaz** [comment]
Hi, can i do it or is it completed?

**Comment by pranay911** [comment]
It is in progress

**Comment by FazeenIjaz** [comment]
> It is in progress

Hey, Can i contribute in it?
