### ISSUE TITLE
Docs: Social media sharing

### ISSUE THREAD

**Issue by tamalCodes** [milancommunity/Milan#1196]
### Description

We would love to have clean and neat documentation or a markdown file that we can share in Discord or any social media basically that talks about our project.

**Points for the same:**

- What is Milan ?
- How to contribute to Milan
- Tech stack of Milan. 

We need to make a proper markdown file that is properly formatted as well containing all these details written in a creative yet easy-to-understand manner along with proper links for how:

- one can contribute to our project 
- sign up on our website and 
- raise issues or join the Milan organization.

`docs > SocialMedia.md`

### Checklist ✅

- [X] I checked and didn't find a similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by Anushkabh** [comment]
@tamalCodes   I WANT TO WORK ON THIS ISSUE UNDER JWOC.. KINDLY ASSIGN

**Comment by tamalCodes** [comment]
Sure, go ahead !

> [!IMPORTANT]  
> Make sure you make the PR to the `main` branch

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
