### ISSUE TITLE
Bug: Google Sign In not working on sign up page

### ISSUE THREAD

**Issue by Himanxu1** [milancommunity/Milan#1197]
### Description

As per the stardard google sign in should work fine , but not working

### Proposed Solution

Should be implemented using firebase

### Screenshots

![Screenshot (6)](https://github.com/milancommunity/Milan/assets/80101755/87c3d0ff-39ec-42a6-a309-7fef97ad68f6)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi @Himanxu1 

We will not be using Firebase as of now because migrating all the data from MongoDB to the Firebase would cause some problems and I want to keep all the data in a singular place for much easier access rather than using two different services.

Also, the workflow just works fine for me, especially in the case of Google authentication can you perhaps take some time to do a small screen recording along with the console open to just tell me where you are getting the error ?

**Comment by Jenis07** [comment]
Hello sir, can you please assign me this issue under JWOC?

**Comment by tamalCodes** [comment]
> Hello sir, can you please assign me this issue under JWOC?

Can you please confirm if the sign-up and signing is breaking ?
To me it looks fine

**Comment by dalalsoham** [comment]
@tamalCodes  
I got this error message while going for signup:
![image](https://github.com/milancommunity/Milan/assets/91643563/b7a4d0c3-f8d8-4496-a7d1-c3b595585d87)

**Comment by tamalCodes** [comment]
Have you went through our documentation on how to set up the backend and also how to set up Google authentication locally ?

**Comment by tamalCodes** [comment]
# Notice 🚩

Hi there, unfortunately, I will have to close this issue, as this issue has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR that are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop an email at milanhub.org@gmail.com, and we will get back to you.

Regards, 
Team Milan.
