### ISSUE TITLE
Feature: Add Light mode & Dark Mode

### ISSUE THREAD

**Issue by Surajit0573** [milancommunity/Milan#1201]
### Description

I want to add a toggle button to toggle between light and dark mode.

### Proposed Solution

I will create this feature using HTML, CSS, JavaScript, and add the button to navbar.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, we do not use plain `HTML, CSS, or JavaScript` - We have initially used ReactJS with Bootstrap. And would like to keep it that way. However, there might be multiple issues if we were to add a dark mode right now.

Anyways do add a dark mode to one single page, let us see how that works out, and then we can go ahead with the same.
> [!IMPORTANT]  
> Make sure you make the PR to the `beta` branch, not `main` 

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by Pranathi2011** [comment]
Hi, I have made PR to the main branch by mistake, what to do now?

**Comment by riteshshukladev** [comment]
Hey @tamalCodes , would love to add this test feature of Light and dark mode as a test on one of the pages, Kindly assign (if not assigned to some other fellow coder).

**Comment by tamalCodes** [comment]
Hi @riteshshukladev this was assigned to @Pranathi2011 previously but looks like they are inactive right now - so would be better if you could go ahead and do it. Remember to take a look at other sites for more information on how to add dark mode or what colors can be added for the same.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
