### ISSUE TITLE
Bug: Link button to GitHub Repo

### ISSUE THREAD

**Issue by tamalCodes** [milancommunity/Milan#1213]
### Description

- Currently, we have nowhere to go from the button in our landing section

### Proposed Solution

- A link can be added to the landing sections button so that on clicking it we can go to the GitHub page

### Screenshots

![image](https://github.com/milancommunity/Milan/assets/72851613/3aefdc15-e616-4b28-ba2c-582629d27f2d)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no).

**Comment by Rishi1314** [comment]
I would like to work on this issue.

**Comment by Radhikarathi04** [comment]
Hi Tamal, I recently discovered this project and was truly captivated by its concept. I'm eager to lend my support and contribute to its development by tackling this specific issue. Could you please confirm whether I can proceed to start working on it? 😊
