### ISSUE TITLE
Bug: 'SignUp' Button Displayed on Events and Shop Pages for Logged-in Users

### ISSUE THREAD

**Issue by ndmaratha** [milancommunity/Milan#1222]
### Description

Currently, a 'SignUp' button is erroneously appearing on the Events and Shop pages even when users are logged in, causing confusion and unnecessary redundancy in the user interface.

### Proposed Solution

 Using conditional rendering based on a useState variable isLoggedIn, which is updated according to whether the user is logged in or not (possibly by accessing a localStorage value), is a common and effective approach to resolve this issue. Here's a summary of your proposed solution:

"I plan to implement conditional rendering based on a useState variable called isLoggedIn, which will be a boolean value. This variable will be updated based on the user's login status, possibly by accessing a value stored in localStorage. By utilizing conditional rendering, I aim to dynamically display or hide the 'SignUp' button on the Events and Shop pages, ensuring that it is only shown when the user is not logged in."

### Screenshots

![already logged in user](https://github.com/milancommunity/Milan/assets/111192743/51ad8228-07c1-4960-a344-90b72853945e)
![showing signup to get notified still](https://github.com/milancommunity/Milan/assets/111192743/2ecaf334-479d-4246-baa8-64ee2c2ef507)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [x] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Hi, that is great, I think we are maintaining a redux store for the same.

- Can you check if the fields in the store are updated properly ?
- And then can you directly add the conditions based on the store value?
