### ISSUE TITLE
enhancing the buttons

### ISSUE THREAD

**Issue by sristy17** [milancommunity/Milan#1226]
### What would you like to share?

Can I enhance the buttons in nav bar?
![Screenshot 2024-02-24 003337](https://github.com/milancommunity/Milan/assets/136837204/265e5e93-2bb6-479e-9968-42472b6f8ccf)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there thanks for being willing to contribute however we are not looking forward to changing our theme as of now so we'll have to close this idea for now. There are more bugs and fixes that we can do on !
