### ISSUE TITLE
[FEATURE] Backround color change on buttons

### ISSUE THREAD

**Issue by jayk-gupta** [MilanCommunity/Milan#643]
### Description

Background color change on hover on buttons can be added.
Can I work on it?

### Screenshots

![Screenshot 2023-04-27 102950](https://user-images.githubusercontent.com/100681165/234763599-cba6e0ae-a5dd-4ccf-8551-75a87dcff37b.png)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi there, this issue seems similar to #644  - so I will be closing it for now, we can discuss about these changes there.
Thanks !
