### ISSUE TITLE
[UI] Socials Icons can be improved

### ISSUE THREAD

**Issue by Deveesh-Shetty** [MilanCommunity/Milan#646]
### What would you like to share?

Currently, the website is using different colors for the social icons.
 
## It would look neat if the logos follow the theme or simple b/w logo may also do the work

![8a18b1c4-5c0d-4b1a-9507-facfc1c1d461](https://user-images.githubusercontent.com/89470104/234916698-894c77c3-abc0-43de-966f-f365de395045.jpeg)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi there, 

Currently, someone is working on revamping the whole Footer section at #623 , i'd like to wait for them to work on it.
In case they make no new improvements to the socials, you can raise an issue.

I am closing this for now, to avoid confusions.
