### ISSUE TITLE
Enhancement:  Add Theme Toggle Functionality

### ISSUE THREAD

**Issue by Saurav-Pant** [MilanCommunity/Milan#656]
### What would you like to share?

I am interested in contributing to this project and I would like to suggest adding a theme toggle function to improve the user experience. A theme toggle function would allow users to switch between a light and dark mode on the website, which can be easier on the eyes and improve accessibility.

I propose adding a toggle button to the top of the page that allows the user to switch between light and dark modes. This could be achieved using CSS variables and JavaScript to dynamically update the color scheme of the website. I believe this would be a valuable addition to the project and would improve the usability of the website.
(https://user-images.githubusercontent.com/103263909/235447446-3eadaaef-4370-4c53-9f76-eef5f590178a.png)

If this feature aligns with the goals and priorities of the project, I would be happy to work on implementing it. Please let me know if you have any questions or concerns.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Well, this looks like a lot of changes, assigning it to you - Do make a Pull request once half way done, and we can keep on working on it collaboratively!

**Comment by IAmTamal** [comment]
Hi there, it has been 2 weeks. I would love to know what changes you are making / would you like to continue with these. Please reply shortly.

**Comment by Saurav-Pant** [comment]
Apologies for not completing the task. I fell ill and can't work on it anymore. I won't be able to complete it due to my health condition. Thank you for understanding.

**Comment by IAmTamal** [comment]
> Apologies for not completing the task. I fell ill and can't work on it anymore. I won't be able to complete it due to my health condition. Thank you for understanding.

I do understand; please take enough rest 💚
Get well soon.

### Notice 🚩
I am **closing** this Pull request because the contributor is inactive. This will be worked upon by someone else.

Thanks,
Tamal.
