### ISSUE TITLE
[BUG] Regitser button text color and spacing issue

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [MilanCommunity/Milan#659]
### Description

The `Register` button text color and spacing should be the same on both `club/register` and `user/register`. The text color on `clubs/register` is greyed out which gives it a feel of the disabled button.

### Screenshots

![Screenshot 2023-05-02 at 5 20 16 PM](https://user-images.githubusercontent.com/88369802/235667215-35a08881-660b-40a8-a39c-a99501e0f10f.png)
![Screenshot 2023-05-02 at 5 19 51 PM](https://user-images.githubusercontent.com/88369802/235667234-9f82c477-5239-4c0a-9057-e572cb0892ae.png)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @Syed-Ali-Abbas-Zaidi , this has already been talked about in #644  - closing this issue.
