### ISSUE TITLE
[FEAT] Use Skeleton Animation Instead of Loading Bars on Cards

### ISSUE THREAD

**Issue by Devansh-365** [MilanCommunity/Milan#692]
### Description

I propose replacing loading bars with skeleton animation on the cards component for the following reasons:

1. Visual engagement: Skeleton animation provides an interactive loading experience, reducing user frustration.
2. Contextual representation: Skeleton animation retains the card's layout, offering a preview of the content to enhance user understanding.
3. Branding and aesthetics: Customizable skeleton animation aligns with our brand and creates a visually appealing loading experience.
4. Differentiation: Skeleton animation sets us apart, providing a modern and sophisticated loading experience.

By implementing skeleton animation, we can improve user experience and make a lasting impression.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Well, that sounds cool - and will make the project much more UX-friendly. You can start working and make a PR. Also is this a part of the GSSOC'23 program? 

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
