### ISSUE TITLE
[FEATURE] Adding animation to buttons

### ISSUE THREAD

**Issue by sumitkr2000** [MilanCommunity/Milan#693]
### Description

Hey @IAmTamal I want to add animation to buttons. Please assign me this issue. Thank you!

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hey what animations are we talking about here ?

**Comment by sumitkr2000** [comment]
@IAmTamal Someone has already applied the hiver effect. 
I want to add contributes list to the readme. Can you assign this issue to me or do I have to create a new one?

**Comment by IAmTamal** [comment]
For any issue check duplicates - since this issue is no longer relevant I will close this.
