### ISSUE TITLE
[FEATURE] Add a "Scroll to Top" floating button

### ISSUE THREAD

**Issue by harshita-kaushik2** [MilanCommunity/Milan#696]
### Description

Hey,
As one can observe from viewing the website, it lacks a scroll-to-top button. Adding this floating button would enhance the user experience of the website.

I'd love to contribute this feature as I have past experience of creating in my personal projects and would request you to assign this issue to me as GSSoC 2023 Contributor.
Thank You :)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Awesome Issue !
You can start working on it slowly and then make a PR - I'll be adding all the relevant tags related to GSSOC after a while.

**Comment by tamalCodes** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.
