### ISSUE TITLE
in event page view button is not working 

### ISSUE THREAD

**Issue by Meenakshiratnawat** [MilanCommunity/Milan#697]
### Description

I can add animated UI pop up card whenever view button is clicked 
,So under GSSOC 23' , I request you to please assign the the task of adding a animated UI pop up card .
Thank you !

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Please provide relevant Screenshots to explain what you want to say.

**Comment by Meenakshiratnawat** [comment]
![IMG-20230523-WA0001](https://github.com/IAmTamal/Milan/assets/90496119/4ad194ed-f2f3-4624-b679-227e996ef583)

**Comment by Meenakshiratnawat** [comment]
When anyone click on view button the image pop out out like this and background will be blur .

**Comment by IAmTamal** [comment]
What you suggested is not clear and we will be making a new page later on for Events - for now, I am closing this to avoid notifications.
