### ISSUE TITLE
[FEATURE] Addition of a *switch to dark mode* button 

### ISSUE THREAD

**Issue by tangorishi** [MilanCommunity/Milan#702]
### Description

As i have seen the website has no dark theme so it would be better from the point of view of user if we add a dark mode, I can work under this isssue!

### Screenshots

![Screenshot (342)](https://github.com/IAmTamal/Milan/assets/110519406/16a4889e-2636-4188-88ab-8bf7ac179b66)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by satyamsinghk** [comment]
Please assign me this issue under GGSOC'23.
Thanks in advance.

**Comment by tangorishi** [comment]
@IAmTamal can you assign me this issue so I can start working on it .

**Comment by IAmTamal** [comment]
Sure go ahead, and assigning you.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by tangorishi** [comment]
hey there I am on it.

**Comment by tamalCodes** [comment]
> hey there I am on it.

That's great to know. You can make a PR once almost there ⚡

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by tamalCodes** [comment]
> This issue has been inactive for a long time I would like to work on this issue Please assign

The last reply from the original contributor was 5 days ago. I generally wait for 2-3 weeks since everyone has a life apart from coding. So please be patient.

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
