### ISSUE TITLE
[FEATURE] Add UserInfo in Profile Page 

### ISSUE THREAD

**Issue by suzy-g38** [MilanCommunity/Milan#709]
### Description

Currently, if you go to the profile page, there will be a form to update your profile. If we can add the necessary information about the user that will make it much more better.

### Screenshots

This is the current profile page

![image](https://github.com/IAmTamal/Milan/assets/62666287/7eb0e487-e883-4dc0-8cfc-2180191d0712)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great concept, however i will lock it for now - so that we can work on #710 first.

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.
