### ISSUE TITLE
[FEATURE] navbar text hover change according to page status

### ISSUE THREAD

**Issue by Git21221** [MilanCommunity/Milan#713]
### Description

If i am in club section then club text color will change in nav.
Assign me this so that I can contribute some.
GSSoC'23, Thanks.

### 🥦 Browser

Opera

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi there, currently we do have an underline feature to indicate in which page I am currently in and TBH it looks clean !
I will be closing this issue.
