### ISSUE TITLE
[FEATURE] Adding some transition effects to the cards

### ISSUE THREAD

**Issue by Heismanish** [MilanCommunity/Milan#714]
### Description

The cards in trending products are looking kinda static, I suppose it can improved by adding some transitions and animations. So would like to implement that feature.

### Screenshots

![Screenshot from 2023-05-21 17-04-33](https://github.com/IAmTamal/Milan/assets/92051445/bb435204-6f7b-4796-b861-0cd166b1bfcb)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Great idea, but what kind of animations and transitions are we talking about here ?

**Comment by tamalCodes** [comment]
### Notice 🚩
I am **closing** this Issue/PR because the contributor is inactive/has not responded for a long time. 
This can be worked upon by someone else, later.


Thanks,
Tamal.

**Comment by SoundaryaKoutharapu** [comment]
Hello @tamalCodes, 
Can I work upon this issue.?
