### ISSUE TITLE
Repairing buttons of Home page on signing up.

### ISSUE THREAD

**Issue by dhrumishah** [MilanCommunity/Milan#718]
### What would you like to share?

After Signing up, the buttons in home page are not aligned

![image](https://github.com/IAmTamal/Milan/assets/84569241/4a4c51ba-85e6-4ff6-a1df-d09912dff554)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by dhrumishah** [comment]
@IAmTamal should I start?

**Comment by IAmTamal** [comment]
> @IAmTamal should I start?

Yeah go for it !

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by dhrumishah** [comment]
Hey @IAmTamal, I'm trying to login to the website when running the code locally but I'm unable to login.

Can you help me how I set it up locally?

**Comment by IAmTamal** [comment]
> Hey @IAmTamal, I'm trying to login to the website when running the code locally but I'm unable to login.
> 
> Can you help me how I set it up locally?

Have you set up the server too ? 
If not , you'd generally want to do it !

**Comment by IAmTamal** [comment]
Hi @dhrumishah now you can try logging in. If you are doing this locally you can make a `.env` file and insert this code there : 

```env
VITE_MILANAPI="https://milan-server.vercel.app"
```

**Comment by dhrumishah** [comment]
> Hi @dhrumishah now you can try logging in. If you are doing this locally you can make a `.env` file and insert this code there : 
> 
> ```env
> VITE_MILANAPI="https://milan-server.vercel.app"
> ```

Thanks, I'll start working now
