### ISSUE TITLE
[FEATURE] Custom Error Page 404

### ISSUE THREAD

**Issue by virajchandra51** [MilanCommunity/Milan#722]
### Description

I will design an Error Page for calls or redirecting to pages which do not exist.

Hello!
I am Viraj Chandra, a proud contributor at GSSoC '23. I would like to the contribute to this project by designing an Error Page for calls or redirecting to pages which do not exist.

Things I will be doing as of now:

- [ ] Designing the error page 404

@IAmTamal  Please Assign me this.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @virajchandra51 , someone else raised this issue 2 days back.
Please CHECK FOR duplicate.
