### ISSUE TITLE
[FEATURE] i would like to add hover effect on card

### ISSUE THREAD

**Issue by Rahul-Bhati** [MilanCommunity/Milan#724]
### Description

please assign me this issue for gssoc23.i want to add animation when cursor hover on product card.

### Screenshots

![Screenshot (1169)](https://github.com/IAmTamal/Milan/assets/76690088/2300add3-8356-42cf-a638-e22657cd46e4)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Here's a similar type of issue : Please follow what you checked `I checked and didn't find similar issue`
