### ISSUE TITLE
[FEATURE] New product cards for the shop page

### ISSUE THREAD

**Issue by KGoutham7214** [MilanCommunity/Milan#729]
### Description

There is a scope of improvement under the shop section  product titles they look completely outdated 

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/80199829/3d36be89-e093-4a12-9eaa-15bf0cd14b82)

### 🥦 Browser

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Cool, this looks like a good issue, please do through #730 to understand the details of all the other work that has been going on related to the shop sections. 

You can start working on re-designing the cards !

**Comment by IAmTamal** [comment]
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.

**Comment by KGoutham7214** [comment]
Sure I'll be making a pr tomorrow with attached screenshot

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
