### ISSUE TITLE
[BUG] Equal Focus On All Buttons

### ISSUE THREAD

**Issue by Souravvmishra** [MilanCommunity/Milan#733]
### Description

All the buttons on the hero section of the website have equal focus of user. As per common practices, one of them should be in higher order of focus in order to attract user to it and act as a CTA. We should try to redesign the buttons in such a way that the active state of one is normal state of other. 

Also the Github Icon should be responsiveness as per the state.

### Screenshots

![Milan _ Home - Brave 23-05-2023 15_34_46](https://github.com/IAmTamal/Milan/assets/89072785/daaa29bb-7205-4bfe-b2ed-47a5fe5366c8)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @Souravvmishra , great idea ⚡
However i want to know, what type of design changes are we talking about, and also how will the structure also change. 
Currently it looks like this:

![image](https://github.com/IAmTamal/Milan/assets/72851613/d74237f0-577a-4b86-84b2-e6c620ece609)

**Comment by Souravvmishra** [comment]
As per common practices, one of them should be in higher order of focus in order to attract user to it and act as a CTA. We should try to redesign the buttons in such a way that the active state of one is normal state of other. Also adjust the logo as per the state of button.

**Comment by tamalCodes** [comment]
Interesting, you can make a PR and then we can I guess further talk about it.

**Comment by Souravvmishra** [comment]
Sorry for the delay. I was out of station for a while. I'll complete it soon.

**Comment by tamalCodes** [comment]
Hi there, please make a PR when possible :)

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
