### ISSUE TITLE
[BUG] Login and Register Form validations and error messages

### ISSUE THREAD

**Issue by Pushpendra33** [MilanCommunity/Milan#735]
### Description
Although the api response messages and notificaions are totally proper but,

Login and Register Forms can be imporve very much by adding validation messages and error messages at right places.
First i will add Global components for Forms, inputs and submit with onChange functionality which will help to improve the accessability and productivity of code.

After that i will add form validation by which proper error message will show on fields.

please assign me this issue to fix under GSSOC'23

### Screenshots

![Screenshot from 2023-05-23 16-07-10](https://github.com/IAmTamal/Milan/assets/108654034/038679de-427b-4a35-8b2d-78f71938f8a5)
![Screenshot from 2023-05-23 16-06-53](https://github.com/IAmTamal/Milan/assets/108654034/bb0b1828-f887-433c-b295-98542c860de6)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Pushpendra33** [comment]
hi 
is anyone here

**Comment by Pushpendra33** [comment]
The first thing which user will see is register and login form so it's good to make them more attractive.
So adding some good validation and error messages will help to improve your productivity of website.
please let me know if you want me to add those points as i have already mentioned above @iakgoog @RXBlade @vancassa @kristiingco

**Comment by IAmTamal** [comment]
> The first thing which user will see is register and login form so it's good to make them more attractive. So adding some good validation and error messages will help to improve your productivity of website. please let me know if you want me to add those points as i have already mentioned above @iakgoog @RXBlade @vancassa @kristiingco

Why are you tagging so many random accounts ?

**Comment by Pushpendra33** [comment]
> > The first thing which user will see is register and login form so it's good to make them more attractive. So adding some good validation and error messages will help to improve your productivity of website. please let me know if you want me to add those points as i have already mentioned above @iakgoog @RXBlade @vancassa @kristiingco
> 
> Why are you tagging so many random accounts ?

sorry for that
looking for response on the issue

**Comment by IAmTamal** [comment]
Thanks for removing those. Please do not tag any accounts. 
Yes the issue seems interesting, make sure you add proper messages and it shouldn't be too lengthy.
Assigning this to you ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Pushpendra33** [comment]
Hi @tamalCodes Thanks for assigning me the issue.
I am working on it.
i have removed json schema validation with my custom validation and error messages.
Added some Global components which help to use inputs and form Globally with custom error messges handling and some Common constants and utilities functions which can help in code.

**Comment by Pushpendra33** [comment]
could you please tell me, where i have to take pull => upstream main or please just tell me the whole procedure

**Comment by Pushpendra33** [comment]
check and review PR from my side
