### ISSUE TITLE
[DOCS] add contributor graph

### ISSUE THREAD

**Issue by S-ishita** [MilanCommunity/Milan#738]
### Description

I want to add contributor graph.Please assign this issue to me

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
We do not need a contributor's graph separately for the readme, so Im closing this issue.
