### ISSUE TITLE
Adding contributors to the README

### ISSUE THREAD

**Issue by mkswagger** [MilanCommunity/Milan#739]
### Description

This issue involves updating the README.md file of the project to include a section for contributors. The purpose of this section is to acknowledge and credit individuals who have contributed to the project.

### Steps to Implement
- Open the README.md file for editing.
- Create a new section titled "Contributors" or "Acknowledgements" at an appropriate location in the README.
- List the names or usernames of the contributors, along with any other relevant information or acknowledgements, such as their contributions or roles.
- If desired, provide links to their profiles or websites.
- Update the README to reflect the changes made.
### Expected Outcome
After implementing these changes, the README will include a dedicated section to acknowledge and credit the contributors who have contributed to the project. This will recognize their efforts and provide visibility to their contributions, fostering a sense of community and collaboration.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by harish343** [comment]
hey can I add all contributors in readme file

**Comment by tamalCodes** [comment]
Hey @mkswagger , great idea but we won't be doing this as with 100+ contributors it would take a lot of space. And contributors would always be seen in the contributor's section.

Thanks for your thoughts, appreciate it ⚡

**Comment by mkswagger** [comment]
Got it !1 Thanks @tamalCodes
