### ISSUE TITLE
[FEATURE] To add hover effect on register page image

### ISSUE THREAD

**Issue by divyansh2212** [MilanCommunity/Milan#742]
### Description

To add hover effect on register page image
Please assign me this issue as GSSOC 2023 contributor.

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/90034292/1df2cde2-5d76-4a5e-a005-63679f2e8fd8)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hey @divyansh2212 , great thought but what kind of hover animations are we talking about ? 
Would be great if you can explain it before proceeding to make a PR !

**Comment by parthpathakpp1** [comment]
@tamalCodes It's been a very long this issue is not fixed. So can you please assign this issue to me? I Will fix this issue. Thank You.

**Comment by tamalCodes** [comment]
Hi @parthpathakpp1 , i will be closing this issue as we are re-vamping the site.

**Comment by parthpathakpp1** [comment]
> Hi @parthpathakpp1 , i will be closing this issue as we are re-vamping the site.

@tamalCodes Ok no issues.
