### ISSUE TITLE
[BUG] Club Page cards redirecting to the bottom of the new page

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [MilanCommunity/Milan#758]
### Description

The cards on the club page when clicked, redirect to the bottom of their details page rather than showing the page from the top.

### Screenshots

<img width="960" alt="image" src="https://github.com/IAmTamal/Milan/assets/70560812/5f65550b-c94d-4dc5-9f1a-5b77e50c80cd">
<img width="960" alt="image" src="https://github.com/IAmTamal/Milan/assets/70560812/1c6143a4-f0ef-423f-84c6-c92eaf91f1d4">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Hi @Ishita-Ghosh-25 , great spot - Assigning to you ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this. Please reply shortly.

**Comment by parthpathakpp1** [comment]
@tamalCodes Can I work on this issue?
