### ISSUE TITLE
[FEATURE] Attach Links

### ISSUE THREAD

**Issue by kumarankit999** [MilanCommunity/Milan#760]
### Description

As we can see below image of Events, If we Click on the View Button there is no responsiveness, and no redirected link which is attached to this button. We also Know that this is now a dummy button, But in Future if we have to add events we also have to provide the Event page Link through the View button which is exact bottom on the preview of the Events. So, that Events can be more and more accessible to all peoples. 

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/111564362/f76d684f-eac6-4ad1-b547-e784b85bb57b)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
True, but for now what do you think we should do ?

**Comment by kumarankit999** [comment]
We Can add random Events with their Event Page

**Comment by IAmTamal** [comment]
We don't have an event's detailed page now. And I don't think adding any external links would be a good idea. So How about we first make an Event's detailed page first ?

**Comment by kumarankit999** [comment]
We Can add any Bengal's Ngo Event, Which is currently happening .I can also add these things. Or We can do one other thing which is that Someone will create a issue with the new event and he will add the event by forking it, Then the Maintainers will Merge it. So, that's how New Events will be added here while contributing to this project. you can also take a reference from Vibey Project, They are how maintaining her project by New contributions. @IAmTamal

**Comment by tamalCodes** [comment]
The concept of Vibey and Milan's event section is different. Vibey is based on promoting and sharing different types of Events, hackathons, and CFP(s). 

The idea of Milan's event section is that the NGOs/Charities will make events themselves with various details and as users we will get to see those events which will be based on Charity events, Fundraising rounds, and so on. There's a huge gap in the thought process for these 2 events. So contributors can't just come in and "contribute events"  !

I guess we will need to wait until there's work on the Events page - which will be done soon.

Thanks for your thoughts ⚡
I will close this issue for now, and once done with the Events Page we can open and work on it !

**Comment by kumarankit999** [comment]
Yes We can do it!!
