### ISSUE TITLE
[BUG] Nav bar should be floating in mobile devices

### ISSUE THREAD

**Issue by I-VipulPandey** [MilanCommunity/Milan#762]
### Description

nav bar is not floating in mobile devices. When clicked on menu icon, the nav bar pushes all the content and takes its place.

The solution is to make nav bar floating so that it doesn't affect any other elements.

Please, assign this issue to me under gssoc'23

### Screenshots

<img width="226" alt="milan bug" src="https://github.com/IAmTamal/Milan/assets/53248489/4aacd93e-9989-4702-8f2d-c8091287c82b">

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Sounds like a great issue, you can go ahead and make a PR, and let's discuss this together ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by Sa91001** [comment]
Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

**Comment by I-VipulPandey** [comment]
> Hi there, it has been a while. I would love to know what changes you are making and/or are working on this.

Hello, been busy with exams lately. I have made the solution and will make a pr in a day or two.

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
