### ISSUE TITLE
[FEATURE] Adding animation to the home page (FRAMER-MOTION)

### ISSUE THREAD

**Issue by ManishaSwain8** [MilanCommunity/Milan#764]
### What would you like to share?

When it is case of Home page, (First impression lasts long)  the home page looks bit off , I would like to add some animation to it (text most probably  ) and when it comes to animation FramerMotion is best other wise anything can be used.
If this changes are req. please do assign it to me under GSSOC 2023 .
Changes will be done in no time  : |)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by IAmTamal** [comment]
Well that sounds like a good idea, can you give me more details on what and how stuffs are gonna change/improve ?

**Comment by ManishaSwain8** [comment]
ok so give me few minutes

**Comment by ManishaSwain8** [comment]
https://github.com/IAmTamal/Milan/assets/96622693/ad74880d-85f8-461e-85a5-dd734489678c

**Comment by ManishaSwain8** [comment]
this not exactly what I am going to do , fade in /fade out etc also I will use,considering the page attractiveness.
This is just an example

**Comment by ManishaSwain8** [comment]
https://github.com/IAmTamal/Milan/assets/96622693/5fc1733b-f541-4982-bb1c-7f6739483cf0

**Comment by ManishaSwain8** [comment]
@IAmTamal 


https://github.com/IAmTamal/Milan/assets/96622693/9f07a148-aa28-4744-9fe9-287ff2d73be3

**Comment by ManishaSwain8** [comment]
@IAmTamal 
Are those changes required...?

**Comment by tamalCodes** [comment]
Hi @ManishaSwain8 , sorry for the delay - got my hands full with exams. 
Please watch [this](https://www.loom.com/share/c9724d656c4f4f6c9b9044f83c4cc16c) video, make sure your **voulume is turned on** - and let me know what you think !

**Comment by ManishaSwain8** [comment]
I understood your requirement I would like to give a try , at the end it will be your choice to add it not, so I will give my 💯 to complete this challenge  : |)
Thanks for the video description ...!

**Comment by tamalCodes** [comment]
Cool, do make a PR ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by ManishaSwain8** [comment]
Hello @tamalCodes ,
I figured out how github animation works, they are using function for onscroll animation and using css animation with hidden visible property(i.e. opacity-0,opacity-1) along with transformX (i.e. used to reposition the element),they are simply hideing and displaying and transforming or repositioning the text from the original position (if u see carefully u can find the original positon of text) .
However adding those animation didinot made the website look wow and reason behind is the color code (in dark background animation looks vibrant and in white background it looks bit off ) , that is why I have added my own elemets to make it eye catchy , hope you get it ...! If you dont like it fell free to reject it .  : |)

https://github.com/tamalCodes/Milan/assets/96622693/e8e2f6d8-4949-4a0b-9e57-dd3ca4b5aaaa

**Comment by tamalCodes** [comment]
Wow from the video that looks super cool 🤩 ,  can you make a PR slowly so that we can review and work on it ?

**Comment by ManishaSwain8** [comment]
yup... glad you got my point ! 
I will soon one the PR after I do some code refactoring of my code.

**Comment by ManishaSwain8** [comment]
> yup... glad you got my point ! I will soon one the PR after I do some code refactoring of my code.

**Comment by ManishaSwain8** [comment]
And one thing I want to ensure , that I have added animation only for once, animation will not go again and again while in view ,
I felt adding animation every time is unnecessary.
So, whats your opinion ?
