### ISSUE TITLE
[FEATURE] Improving Shop Page

### ISSUE THREAD

**Issue by sumitkr2000** [MilanCommunity/Milan#768]
### Description

Hey @IAmTamal I want to improve the UI of the SHop page. Please assign me this issue. Thank you!

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, currently there are a lot of changes that are being done with respect to our integrated shop. So I would recommend waiting until all those are taken care of, because with all the API integrations and stuff - the UI is kind of messy.

**Comment by sumitkr2000** [comment]
@tamalCodes Ok bro np!

**Comment by sumitkr2000** [comment]
Hey, @tamalCodes Are the changes still not done?

**Comment by sumitkr2000** [comment]
Can I start working on this issue? @tamalCodes
