### ISSUE TITLE
[FEATURE] API to delete a product

### ISSUE THREAD

**Issue by Nitish-hack** [MilanCommunity/Milan#770]
### Description

Thinking to add and API to delete a product from the database using id of the product 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi, @Nitish-hack I appreciate your motivation to work, but please we need to take things slowly and step by step.

You currently have #766 and #701 assigned to you, please make sure those are merged and then we can proceed with these. I will be temporarily putting these on hold. Thanks.
