### ISSUE TITLE
Missing back-to-top button

### ISSUE THREAD

**Issue by AlabhyaG** [MilanCommunity/Milan#776]
### Description

The webpage does not have any back-to-top button.
Adding it will ease the user to go to top of the page without much hassle

### 🥦 Browser

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This is already been worked on #696 , please do not raise duplicates. 
Thanks.
