### ISSUE TITLE
[BUG]  Error on /clubs

### ISSUE THREAD

**Issue by programerr01** [MilanCommunity/Milan#777]
### Description

Undefined Error  is coming on ` /club` page when you click on any event

### Screenshots

![image](https://github.com/IAmTamal/Milan/assets/61112300/2b20a6bf-3e4f-40a1-9ba7-55bda482d1a0)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by guptaanshik1** [comment]
Can you please assign me this issue. I will look into this

**Comment by tamalCodes** [comment]
Hi @programerr01 - this is happening because right now we do not have an events card and work is going on with it currently. I am closing this issue to avoid confusions.

Thanks.
