### ISSUE TITLE
[FEATURE] adding company name beside logo in footer section

### ISSUE THREAD

**Issue by Iamdivyak** [MilanCommunity/Milan#784]
### Description

company name beside the logo in the footer section is not available.

kindly assign it to me under gssoc'23

### Screenshots

<img width="953" alt="image" src="https://github.com/tamalCodes/Milan/assets/102896170/bf3460a3-faf1-44c5-b5b8-eafb1abfd235">

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, i think the logo in the footer is self-sufficient, and with the name in the navbar, that would be enough!
