### ISSUE TITLE
[FEATURE] Add Joi Validation, Error Handling and Server Structure

### ISSUE THREAD

**Issue by madhur87** [MilanCommunity/Milan#785]
### Is your feature request related to a problem ? Please describe. ✍️

```bash
Enhancement

Here are some benefits of using Joi validator:

1. The joi validator is feature rich and has a lot of rules for validating complex data-structures
2. It can also handle errors properly.
```

### Describe breifly how would you implement the same.

```bash
1. Add Joi Package
2. Create a Validation Folder
3. Create Validate Schema with Require Conditions.
4. Add in API to Validate the Payload.
5. Create a Controllers Folder and move logic,
```

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by madhur87** [comment]
@tamalCodes Please assign!

**Comment by tamalCodes** [comment]
Hi @madhur87 , it would be better if you explain to me what is `joi validation` - I do not understand anything at all. Please give a detailed explanation.

**Comment by madhur87** [comment]
Joi is help to validate the payload, it help to handling the error handling with proper error message, for example you have triggered POST/PUT API with payload so at the moment help to validate the payload with condition like name will be string, phone will be number with minimum 10 digit, if any user send the wrong payload like phone digit will be 9 then Joi will be help to validate the payload and return proper error message like phone will be require 10 digit.

**Comment by tamalCodes** [comment]
Interestingly, from what I understood it is a schema validation library which makes validation much easier.
So what I would recommend is to, first of all, do the auth part. Such that the schema, and API for the User and club are properly validated.

Once it is done then we can proceed with others too. Assigning this to you ⚡

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**
