### ISSUE TITLE
[FEATURE] Adding a Slow loader

### ISSUE THREAD

**Issue by kartikkc** [MilanCommunity/Milan#786]
### Description

I am from GSSOC'23 and I have noticed that, 

A slow loader animation can be added to the website which will make it look more seamless and will go with the design of the website.

I want to work on this. Can you assign me this issue?

### 🥦 Browser

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi, can you perhaps explain where are you planning to add it ?

**Comment by kartikkc** [comment]
@tamalCodes I haven't noticed it as it didn't show up on my machine!

**Comment by tamalCodes** [comment]
Oh, that's fine. But since we already have it  - there's no point in adding it back again. 
Closing the issue, thanks for your time !
