### ISSUE TITLE
The background of the site is very plain

### ISSUE THREAD

**Issue by harsh-kumar213** [MilanCommunity/Milan#794]
### Description

the background of the site is very plain. Providing someone help is a work which showcase it. I can add some backgrounds to make it look much better

Please assign me

### Browser 🥦

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi this looks like a Frontend revamp, and we are currently not looking to do so. I will close this now, maybe you can open up a discussion so that people can contribute their ideas in, and after we have a lot of changes for the background we can proceed.
