### ISSUE TITLE
[FEATURE] Add night mode for the website

### ISSUE THREAD

**Issue by PVBharadwaj** [MilanCommunity/Milan#795]
### Description

The website is only having a light theme. I would like to add a dark theme also, to the website.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This is worked upon in #702 , please do not raise duplicates. Thanks.
