### ISSUE TITLE
Style: Enhance card ui of the clubs page.

### ISSUE THREAD

**Issue by Pragati-3003** [MilanCommunity/Milan#798]
### Description

I Would like to change the ui of the cards in the clubs page.
![milan_club](https://github.com/tamalCodes/Milan/assets/132778037/5e06b1e4-edd0-4c7d-ad5a-2b4df541e08e)
I would like to add cool effects ,box shadows to make it more attractive. 
So,please assign this issue to me under GSSOC'23.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Pragati-3003 , we are not looking for design changes right now, especially for the Clubs page - so I'll have to close this issue.
