### ISSUE TITLE
[FEATURE] Addition of social media icons to share a particular donation card to other users world wide 

### ISSUE THREAD

**Issue by shravan-das** [MilanCommunity/Milan#800]
### Description

The addition of social media icons allows users to easily share a particular donation cloud with other users on various social media platforms. This feature enhances the visibility and reach of the donation cloud, enabling users to spread awareness and encourage others to contribute to the cause.

(thinking of adding icons in bottom right of help us grow 
if there are any suggestion where should i add it then please suggest)

### Screenshots

![Screenshot (109)](https://github.com/tamalCodes/Milan/assets/100745475/39e8bbd0-d0ae-4e61-bf81-9d0ed6ae3807)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
The concept sounds fun, can you perhaps elaborate on the details for adding a social icon ?

**Comment by shravan-das** [comment]
for sure sir...
![Screenshot (111)](https://github.com/tamalCodes/Milan/assets/100745475/521d43fd-292e-42c1-ac0b-84fbb2f867d7)
in the screenshot above you can see social media icons like linkedin,whatsapp,instagram placed on bottom right of share 

if a user wants to share a particular ngo as shown in below screenshot then he/she can share
![Screenshot (112)](https://github.com/tamalCodes/Milan/assets/100745475/b6d293ee-c124-4083-9e07-e8903ae2d54f)

react-share is a package of react used to achieve the above tasks

**Comment by tamalCodes** [comment]
Oh wow, that sounds good ! 
You can start working on it ⚡


**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by shravan-das** [comment]
thank you very much sir..Starting working on this feature asap

**Comment by tamalCodes** [comment]
### Let's catch up !
Hi there, it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at tamalcodes@gmail.com.

**Comment by shravan-das** [comment]
Actualy i have my endsem exams ongoing
I would like to get unassigned on this issue as it may take long time for me to catch up on this issue..
If anyone wants to work on this issue then they can!

**Comment by Sahilll15** [comment]
can i work on this issue??

**Comment by tamalCodes** [comment]
Hi @shravan-das thanks for informing me about the current scenario. As it goes I will be closing this issue because TBH there are a lot of things to be done before adding the share cards option, thankyou so much for your time.

Regards, 
Team Milan.
