### ISSUE TITLE
[FEATURE] Add an option for donation from visitors

### ISSUE THREAD

**Issue by Vedant-MAHAjan** [MilanCommunity/Milan#801]
### Description

A brief compelling story with a warm nudge to make donation would be really useful for this site

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Vedant-MAHAjan , can you perhaps explain in Detail what are you trying to implement as we already have a donation system in place?

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
