### ISSUE TITLE
[BUG] Profile pic not aligned on Navbar on smaller devices.

### ISSUE THREAD

**Issue by atharvasankdm** [MilanCommunity/Milan#802]
### Description

the profile pic is not well aligned on devices of dimension(<=768px) and some minor style refactoring needed for the navbar elements.

Kindly assign me this issue under GSSOC contributor.

### Screenshots

![milan_issue_2](https://github.com/tamalCodes/Milan/assets/85010913/cf297fa1-8f7e-4d72-838a-07cabe212180)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Great bug spot, you can go ahead and make a PR to fix this. 

**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-), without proper format the PR might be closed.**

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
