### ISSUE TITLE
[FEATURE]adding a feed back section [GSSOC;23]

### ISSUE THREAD

**Issue by kharshita590** [MilanCommunity/Milan#803]
### Description

I WANT TO ADD A FEED BACK SECTION WHERE YOUR USER CAN SHARE THEIR FEEDBACK.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @kharshita590 , what type of feedback are we talking about and where do we plan on adding it ?

**Comment by kharshita590** [comment]
@tamalCodes HERE I WILL ADD A FEEDBACK SECTION , IN WHICH THE USER WILL WRITE THEIR FEEDBACK AND THAT WILL BE SENT TO YOUR EMAIL

**Comment by tamalCodes** [comment]
Hi @kharshita590 , i don't think that feature will be needed, as we already have a functional `report` feature. 
Thanks.
