### ISSUE TITLE
Style: Enhance UI of the Events page.

### ISSUE THREAD

**Issue by Pragati-3003** [MilanCommunity/Milan#808]
### Description

I would like  to add some ui effects on the events page.

So,please assign this to me under gssoc'23.

### Screenshots

![milan2](https://github.com/tamalCodes/Milan/assets/132778037/7e936423-a276-43d1-927c-d7bf4260e9ce)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Pragati-3003 , we are not looking to further improve the UI of our clubs/events page at the moment, so I will have to close this Issue. Thankyou so much for your time.
