### ISSUE TITLE
[FEATURE] Create Testimonial Section for the website

### ISSUE THREAD

**Issue by abhi03ruchi** [MilanCommunity/Milan#810]
### Description

I would like to create  Testimonial Section for the website. 

The testimonial section on the website will provide a valuable advantage in showcasing the positive experiences and feedback from satisfied customers or clients. By featuring testimonials, a website gains the advantage of instilling trust, attracting new customers, and reinforcing the reputation of the brand. It creates a sense of authenticity and reliability, ultimately leading to increased confidence and a higher likelihood of conversions.

Plz, assign me this task under gssoc'23.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there @abhi03ruchi, I don't think we will need that feature because we are not a product or a company that is providing any kind of different services, we are more of a platform. So I am not sure if a testimonial section  even makes sense.
