### ISSUE TITLE
[FEATURE] Add hover effect on card items

### ISSUE THREAD

**Issue by Soulpurr** [MilanCommunity/Milan#812]
### Description

Would like to add a hover effect on trending products so that on pointing cursor it eases in or out.

### Screenshots

![Screenshot_2023-06-04-21-47-03-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/tamalCodes/Milan/assets/92094765/064bd845-0539-463e-8417-2da814894962)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, currently there is a lot of work going on, especially the UI work on #729. So I would currently close this issue.
