### ISSUE TITLE
[GSSOC'23] [OTHER] Remove the demo card from Production

### ISSUE THREAD

**Issue by ayushkumarbhadani** [MilanCommunity/Milan#821]
### What would you like to share?

Hey @tamalCodes, I saw a hello world card on the events page. I think this should not be present in the production and be removed. 

<img width="314" alt="Screenshot 2023-06-06 at 6 49 38 PM" src="https://github.com/tamalCodes/Milan/assets/73775939/f3990e78-0b95-4fad-bf7f-6480a55ee844">

I would like to work on it, kindly assign this task to me under GSSOC'23 Label, please.
### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @ayushkumarbhadani , thanks for noticing - the moderation team will soon remove the card from the Database. 
Thanks once again for bringing this into our notice.
