### ISSUE TITLE
[BUG] navbar alignment and responsiveness

### ISSUE THREAD

**Issue by rahulaarora** [MilanCommunity/Milan#825]
### Description

- The contents(links) of the navbar are not properly centred aligned after signing in
- The navbar is not responsive on Laptop-1024px width without a user logged in

### Screenshots

<img width="998" alt="Screenshot 2023-06-07 at 12 38 46 PM" src="https://github.com/tamalCodes/Milan/assets/24794534/bf207c31-c58d-4a97-9515-7fd0e046f170">

<img width="943" alt="Screenshot 2023-06-07 at 12 38 13 PM" src="https://github.com/tamalCodes/Milan/assets/24794534/dadc7cd5-002d-4b66-ac02-5115f7ba2df2">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Sorry about the delay - you can start working on this.

### Remember, Good PR makes a Good Developer !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits.
**Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).**

Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.
