### ISSUE TITLE
A back to top button

### ISSUE THREAD

**Issue by medhacodes** [MilanCommunity/Milan#833]
### Description

A smooth working back to top button which is currently not present in the website.
@tamalCodes please assign this issue to me.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @medhacodes , you can start working on it now !

**Comment by medhacodes** [comment]
Hey @tamalCodes thankyou for assigning the issue to me! I have started working on it.

**Comment by medhacodes** [comment]
Hey @tamalCodes, thankyou for assigning this issue to me. I will work on it. Apologies for the late reply.

**Comment by sumitkr2000** [comment]
Hey @tamalCodes It seems that he is not working on this issue anymore. Can I please work on this issue? Thank you!

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi @medhacodes , unfortunately, I have to close this Issue/PR, as there is no work currently going on for the same. There might be more Issues/PR which are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before closing.

If you think that this is a mistake, please drop a mail at tamalcodes@gmail.com, and we will get back to you.

Regards, 
Team Milan.
