### ISSUE TITLE
[FEATURE] Adding a contact us section

### ISSUE THREAD

**Issue by kharshita590** [MilanCommunity/Milan#837]
### Description

I want to add a contact us section 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @kharshita590 , we already do have a contact page [here](https://milaan.vercel.app/contact) - so I don't think there's any need to add a contact us section. Thanks for your thoughts !
