### ISSUE TITLE
[FEATURE] Adding background color to the navigation bar. 

### ISSUE THREAD

**Issue by Srija-Burugula** [MilanCommunity/Milan#840]
### Description

In the current version of the website, there is no background color to the navigation bar. Adding this would enhance the UI. I would like to work on this issue under GSSoC'23. Please assign this issue to me.  

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, this issue is related to #840 - since you are working on that already, you can add blur background to the navbar there itself. No need to create another issue for the same.
