### ISSUE TITLE
[FEATURE] NavBar options more attractive

### ISSUE THREAD

**Issue by kaashikaagrawal** [MilanCommunity/Milan#841]
### Description

When the user hovers over the different navbar options - Home,Clubs,Events,Shops the buttons can dynamically change. For example an orange underline can follow the mouse.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by kaashikaagrawal** [comment]
please assign me this issue

**Comment by tamalCodes** [comment]
Hi @kaashikaagrawal , we do have a hover feature so I don't think we need something more. I will be closing this issue - thank you so much for your time to do it !
