### ISSUE TITLE
[FEATURE] Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [MilanCommunity/Milan#853]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

I would like to implement lazy loading to the website.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi , currently you have  #855 and #856  assigned, please complete those and then we can start to work on this.
