### ISSUE TITLE
[FEATURE] Typewriter effect in the heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [MilanCommunity/Milan#858]
### Description

*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

@tamalCodes Please assign me this issue under gssoc'23

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/104912087/24b90284-0eb4-4082-84f1-a50a427099bf)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Anshika-Jain02 , we are not looking for such animations on our website - so I will have to close this issue.
