### ISSUE TITLE
[FEATURE] redesign cards in event/clubs/shop page

### ISSUE THREAD

**Issue by mandliyarajendra11** [MilanCommunity/Milan#865]
### Description

![Screenshot (117)](https://github.com/tamalCodes/Milan/assets/119125519/b86a0c80-0008-43bc-9831-a58cfae688a5)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @mandliyarajendra11 , can you please explain what you want to do ?

**Comment by mandliyarajendra11** [comment]
> Hi @mandliyarajendra11 , can you please explain what you want to do ?

ui update - redesign card of event , clubs , shop page

**Comment by mandliyarajendra11** [comment]
> Interesting, can you perhaps create a prototype? That way it would be easier to understand.


https://github.com/tamalCodes/Milan/assets/119125519/8da0c9c4-05b5-44ab-b25e-76df9a1bbeca

**Comment by tamalCodes** [comment]
Wow that looks nice, but TBH for the cards we have, I think we will keep the cards as it is for now. Thanks for your time
