### ISSUE TITLE
[BUG] A small issue under Events tab

### ISSUE THREAD

**Issue by swapn652** [MilanCommunity/Milan#869]
### Description

Under **Events** tab, for the third event, the time format doesn't seem right.

### Screenshots

<img width="373" alt="Screenshot 2023-06-19 at 7 51 49 PM" src="https://github.com/tamalCodes/Milan/assets/70851202/664dd525-c679-49a3-8d8d-eb1d617e6645">

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
That is not time, that is the description they wrote - the moderation team will fix these. Thanks.
