### ISSUE TITLE
Add contributors graph

### ISSUE THREAD

**Issue by VSatwika** [MilanCommunity/Milan#871]
### Description

- I would like to add contributors graph in the ReadMe.md file.
- Could this issue be assigned to me under GSSoC'23?

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, we are not currently looking to modify our Readme file for these changes + the contributors can easily be seen in the `Contributors` section. So I will have to close this issue !
