### ISSUE TITLE
[FEATURE] Login Form Alignment Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [MilanCommunity/Milan#873]
### Description

The design of the form is really nice but it can be improved by making some alignment adjustments in the form which will add significant amount of good impact in the website. By aligning the heading, and button into the center, we can improve the design.

### Screenshots

**Current Alignment** 
![milan (2)](https://github.com/tamalCodes/Milan/assets/115794049/bcd6abf9-3724-4051-b448-9396a262c292)
**Expected Updated Alignment**
![milan (1)](https://github.com/tamalCodes/Milan/assets/115794049/96ea69d7-9b5a-47d8-b2ff-c60306f92f8e)
malCodes/Milan/assets/115794049/d4bb596b-2350-48bf-862c-99781e178aea)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @iamRabia-N , we are currently revamping the whole authentication page so this is no longer relevant. 
Take a look at the latest changes [here](https://www.linkedin.com/feed/update/urn:li:activity:7078669098183790592/).
