### ISSUE TITLE
[BUG] CSS Validation Issue

### ISSUE THREAD

**Issue by itshypon** [MilanCommunity/Milan#885]
### Description

At some part of code, values of CSS properties is not correct. I would like to fix it.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/30335924/38f8c2ad-fe20-42b8-b60c-bfa0cd19b9f6)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Great issue, i would put this on-hold right now and this can be worked on as soon as #892 is merged to the main branch. Putting this temporarily on hold.

**Comment by tamalCodes** [comment]
Hi @itshypon , you can start working on it.

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
