### ISSUE TITLE
[FEAT] Adding dark mode

### ISSUE THREAD

**Issue by akshaysoni10** [MilanCommunity/Milan#886]
### Description

I want to add dark mode feature to make website more catchy. Please assign me this task under **GSSoC'23**.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @akshaysoni10 , that sounds good - well instead of a full pitch-black background I am looking for something different, like matte, or something like that. What do you suggest?

**Comment by tamalCodes** [comment]
Well, we can start working on those then. Make a draft PR to `beta-dark-mode` branch, not the main branch.

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
