### ISSUE TITLE
[FEATURE]: Contribute to Milan button need styling

### ISSUE THREAD

**Issue by HimanshuNarware** [MilanCommunity/Milan#887]
### Description

The Contribute to Milan button need styling, The size of the button is not match the other ones

### Screenshots

![64](https://github.com/tamalCodes/Milan/assets/83147410/b8d54d3a-77e4-4b6a-bab3-afb882f5e182)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This was already fixed by me in #892 

![image](https://github.com/tamalCodes/Milan/assets/72851613/81894d8e-f4c9-4e22-abec-7435537b142e)
