### ISSUE TITLE
[FEATURE] Add lazy loading

### ISSUE THREAD

**Issue by sumitkr2000** [MilanCommunity/Milan#888]
### Description

Hey, I want to add lazy loading to the website. The benefits of lazy loading include:

- **Reduces initial load time –** Lazy loading a webpage reduces page weight, allowing for a quicker [page load time].

- **Bandwidth conservation –** Lazy loading conserves bandwidth by delivering content to users only if it’s requested.

- **System resource conservation –** Lazy loading conserves both server and client resources, because only some of the images, Jav

Although there is a similar issue but the conversation was locked so I created a new one. Can you assign me this issue, please?

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by sumitkr2000** [comment]
@tamalCodes Please assign me this issue.

**Comment by tamalCodes** [comment]
Already been worked on in #853
