### ISSUE TITLE
[BUG] Add Spacing in Registration Form

### ISSUE THREAD

**Issue by Sriparno08** [MilanCommunity/Milan#889]
### Description

As you can see in the below screenshot, the heading in the registration form for clubs/NGOs is not fully visible as it is getting layered over by the navbar. If we add some spacing before the heading, it will be clearly visible.

### Screenshots

![Screenshot 2023-06-24 201036](https://github.com/tamalCodes/Milan/assets/89148144/885a88f3-fdb3-4bc1-8fe3-fa383058f940)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Riyazul555** [comment]
Hey @Sriparno08 and @tamalCodes I want to work on this issue ....please assign it to me under GSSOC 23

**Comment by tamalCodes** [comment]
Hi @Sriparno08 , we are revamping the auth pages, so please do wait until then. I will have to close this issue to avoid any conflicts.
