### ISSUE TITLE
[BUG] Add validations on signup

### ISSUE THREAD

**Issue by Rishita1304** [MilanCommunity/Milan#897]
### Description

I want to add multiple validations on sign up page. Please assign me this issue.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Rishita1304 , this has already been done [here](https://github.com/tamalCodes/Milan/pull/892) do take a look.
Please refrain from raising duplicates.
