### ISSUE TITLE
ADD PROPER IMAGE AND DESCRIPTION FOR THE CARDS IN EVENTS SECTION

### ISSUE THREAD

**Issue by Mansi209aps** [MilanCommunity/Milan#900]
### Description

I will add proper photos and names for the events section. Please assign me this issue :))

### Screenshots

<img width="803" alt="image" src="https://github.com/tamalCodes/Milan/assets/78530251/d21c7418-8d76-447e-9d0e-2e7a1297210d">

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
These were dynamically created events. We cannot add stuffs to it manually.
