### ISSUE TITLE
[FEATURE] Add a scroll-up button on all pages (GSSoC'23)

### ISSUE THREAD

**Issue by abrehan2** [MilanCommunity/Milan#914]
### Description

Hi, I will add a scroll-up button utilizing React.js for a better user experiences.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/100872683/8b44e67a-1613-43ee-a246-cdf10827f838)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This issue is already been worked on in #833. Please check before raising one.

**Comment by abrehan2** [comment]
Should I work on it?
