### ISSUE TITLE
[FEATURE] Chat bot AI

### ISSUE THREAD

**Issue by shraddha761** [MilanCommunity/Milan#915]
### Description

Adding GPT ChatBot
you have to add your own API from Chat-GPT reason API is a personal token  and I'll also add a cloumn for that in the code so you just have to paste the API and it will run for you.

I'll drop the instructions while raise a PR
& I'll add a Step to get API while raising a PR

Assign this issue to me under GSSOC'23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
This sounds like an intresting issue but TBH I don't think we need this kind of features right now. So I will have to close this, Thank you so much for raising it !
