### ISSUE TITLE
adding footer to the home page

### ISSUE THREAD

**Issue by anuza08** [MilanCommunity/Milan#920]
### Description

adding footer to the home page.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Thanks for raising the issue - that will be added once I make some changes to it.
