### ISSUE TITLE
[FEATURE] Adding contributions page

### ISSUE THREAD

**Issue by anamika7153** [MilanCommunity/Milan#921]
### I'm in GSSoC'23

- I would like to add a contributions page displaying contributors and their social media handles.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
As the contributors grow - there can be thousands of them. So having so many data and managing them can be a task. Also contributors are visible in the contributors section, putting them into the product makes no sense.
