### ISSUE TITLE
[BUG] Text overlapping for smaller views

### ISSUE THREAD

**Issue by krutikajichkar** [MilanCommunity/Milan#925]
### What would you like to share?

Text is overlapping on contribute to Milan Button , i want to fix that , please assign me this under gssoc'23

![Screenshot (136)](https://github.com/tamalCodes/Milan/assets/93243210/1f8b49aa-056e-4291-a6cd-3eb73db8e083)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by ManashAnand** [comment]
I would like to work on this issue as well 
Can you assign it to me .

**Comment by 0rigin-c0de** [comment]
I also want to work on this

**Comment by tamalCodes** [comment]
Hi @krutikajichkar , go ahead with the issue - make sure that the changes you are making to the overflow must not change any spacings and so on.

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.
