### ISSUE TITLE
[FEATURE] Migrate website to NextJs

### ISSUE THREAD

**Issue by s2sharpit** [MilanCommunity/Milan#933]
### Description

Currently, the codebase is in react...I would like to migrate it to the next.js

I would like to work on it under gssoc23

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @s2sharpit , for now, we would keep the tech stack as it is, and not think about moving to a completely different thing. Thanks.

**Comment by s2sharpit** [comment]
> Hi @s2sharpit , for now, we would keep the tech stack as it is, and not think about moving to a completely different thing. Thanks.

Thanks for your response @tamalCodes, but Next.js is not a completely different tech stack. It is built on top of React which solves problem which exist in react and improve the website to look lik3 professional.
By the way, Thankyou again for your response.

**Comment by tamalCodes** [comment]
Hi @s2sharpit , i know what NextJS is. 
Frameworks are made to be used when needed, and not to be used everywhere. As per the project size - there are hardly multiple features that need to render stuff via server-side, or to fetch data in different manner and so on. In short, even if we were to use the framework, there won't be any advantages of using the same.

Alot of startups have their product still profitable and highly optimized with react, the same goes for us. It works now, when time and situation calls we'll definitely look for help to upgrade to Next !

**Comment by s2sharpit** [comment]
Hi @tamalCodes, thank you for providing your insights. I completely understand and respect your decision to stick with React for the project. I apologize if my previous messages seemed insistent. I simply wanted to highlight the potential benefits of Next.js based on my understanding and the [recommendations from the React](https://react.dev/learn/start-a-new-react-project). However, I fully trust your judgment and the project's needs. Thank you again for your response, and I genuinely appreciate your willingness to consider my suggestion. Have a great day! 😊
