### ISSUE TITLE
[FEATURE]  Want to add Contributor list page in the website.

### ISSUE THREAD

**Issue by HimanshuNarware** [MilanCommunity/Milan#937]
### Description

I want to add a webpage that shows the name and the profile image of the contributor of Milan.
We can add Contributor element on the navbar  which is directed to the contributor page

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
As the contributors grow - there can be thousands of them. So having so many data and managing them can be a task. Also contributors are visible in the contributors section, putting them into the product makes no sense.
