### ISSUE TITLE
[FEATURE] scroll to top button 

### ISSUE THREAD

**Issue by sumitkr2000** [MilanCommunity/Milan#939]
### Description

Hey @tamalCodes I want to add scroll to top button. Please assign me this issue. Thank you!

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
WIP: #908

**Comment by sumitkr2000** [comment]
> WIP: #908

Please let me know if he is not working
