### ISSUE TITLE
Implementation of Swagger API for better testing.

### ISSUE THREAD

**Issue by Saksham1005** [MilanCommunity/Milan#947]
### What would you like to share?

Swagger API will help expose all the routes on a single URL. Thus helping developers to quickly test the APIs developed, that too on the browser itself.

A Sample of Swagger API is as follows-
![image](https://github.com/tamalCodes/Milan/assets/70437462/7a1d5985-1d75-4664-807d-8510479173df)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Saksham1005** [comment]
Please assign the issue to me under GSSOC 23.

**Comment by tamalCodes** [comment]
Hi @Saksham1005 , thanks for the issue TBH i have already started the work on swagger, and documenting API properly a week back. I will be closing this issue for now !
