### ISSUE TITLE
[OTHER]: REVAMP DONATION FORM 🪄

### ISSUE THREAD

**Issue by 0xabdulkhalid** [MilanCommunity/Milan#950]
### What would you like to share?

- I would like to revamp the donation form on the clubs page, the current design of the form lacks proper padding and styling.

## Screenshots

| CURRENT STATE | DESIRED STATE V1| DESIRED STATE V2 |
| :---: | :---: | :---: |
| ![image](https://github.com/tamalCodes/Milan/assets/92252895/89a3de04-7ad3-416c-b7ea-ac51aaa7dd78) | ![Screenshot 2023-07-22 at 19-15-08 Milan](https://github.com/tamalCodes/Milan/assets/92252895/430aacf9-3c37-424a-85a6-d087621e5412) | ![Screenshot 2023-07-22 at 19-18-57 Milan](https://github.com/tamalCodes/Milan/assets/92252895/1090df7f-5825-460e-aa41-edf2ca374ec9) |

### 🥦 Browser

Mozilla Firefox

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by 0xabdulkhalid** [comment]
Hey there @tamalCodes 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by 0xabdulkhalid** [comment]
@tamalCodes can i get any update ?

**Comment by tamalCodes** [comment]
Please raise this issue under `bugs`
