### ISSUE TITLE
Buy Me Coffee button

### ISSUE THREAD

**Issue by Harshu467** [MilanCommunity/Milan#952]
### Description

As this is open source project to enhance , project needs buy me button to grow

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/89975347/356f8843-7c18-42d9-a110-025def30231b)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Harshu467 , we do not need a buy me a coffee button as this is an Opensource project and not something personal, instead you can contribute to our project by directly sponsoring me, though the sponsor button.
