### ISSUE TITLE
Top up button

### ISSUE THREAD

**Issue by Harshu467** [MilanCommunity/Milan#953]
### Description

There is need of Top to up button which help to go to top of website

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/89975347/8538df13-f876-472f-9fe3-70a049c06f85)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi there, please do not raise duplicates. It is already been worked on at #908
