### ISSUE TITLE
[DOCS]:  Updates to .gitignore

### ISSUE THREAD

**Issue by Anmol-Baranwal** [MilanCommunity/Milan#966]
### What would you like to share?

Changes that I will make:

1. Remove `.DS_STORE` as it is not needed in any repository and stores personal preferences locally.
![image](https://github.com/tamalCodes/Milan/assets/74038190/5972975a-2564-4dc1-8ac0-59f4aea2d1e5)

2. Update `.gitignore` by adding a vast range of unnecessary files, mainly for the tech stack of this codebase.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Sounds good to me, you can start working, on the changes. Since this is related to https://github.com/tamalCodes/Milan/labels/%F0%9F%93%84%20aspect%3A%20docs would you like to take up some more changes related to documentations ?

**Comment by Anmol-Baranwal** [comment]
> Sounds good to me, you can start working, on the changes. Since this is related to [ 📄 aspect: docs](https://github.com/tamalCodes/Milan/labels/%F0%9F%93%84%20aspect%3A%20docs) This issue is related to documentation fixes. would you like to take up some more changes related to documentations ?

No, I will not be contributing after today. This will mark my final contribution to the codebase for the foreseeable future.
