### ISSUE TITLE
[DOCS] Make the frontend and backend setup into shell commands

### ISSUE THREAD

**Issue by karthiknadar1204** [MilanCommunity/Milan#980]
### Description

Currently in the link that directs us to setup the frontend and backend locally has a bunch of commands that require manual copying, I was thinking of making them into shell commands to copy them directly and ease the task of the contributor

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by tamalCodes** [comment]
Hey @karthiknadar1204 , can you please explain what do mean by `making them into shell commands to copy them directly and ease the task of the contributor` ?

**Comment by karthiknadar1204** [comment]
Like right now the commands are like the one you have presented, I propose to turn them all into something like this

<img width="852" alt="Screenshot 2023-07-30 at 9 19 00 PM" src="https://github.com/tamalCodes/Milan/assets/95973644/a2d0f119-4275-4247-b66b-f03d1232e8ff">


Instead of copying it manually using the cursor, I was thinking of making it easier by making them into the one in the above picture

**Comment by tamalCodes** [comment]
Sounds good, you can go ahead with it !

### Remember, Good PR makes you a Good contributor !

We at Milan work hard to maintain the structure, and use conventional Pull request titles and commits. Without a proper template for the PR, not following the guidelines and spam might get the pull request closed, or banned.


- Please make sure that you have read our documentation on [Commiting guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#commits-) and [Pull request guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md#pull-requests-).

- Once you have done the changes you can `request` a review. If I suggest changes again, do those and `request` a review again.

- Make sure you DO NOT modify the PR template that we have, use it as it is.

- Last but not least, be patient. It takes a while to review the changes and get it merged.

**Comment by karthiknadar1204** [comment]
Thank you
