### ISSUE TITLE
[BUG] Report a Bug Form Not Working Due to Incorrect URL in Client Side

### ISSUE THREAD

**Issue by Nishitbaria** [MilanCommunity/Milan#986]
### Description

Currently, the "Report a Bug" form in Milan is not functioning as expected due to an incorrect URL specified in the client-side code. As a result, users are unable to submit bug reports, leading to a degradation in the bug tracking and resolution process. This issue needs to be addressed to ensure that users can efficiently report bugs and improve the overall stability of the application.

**Bug Details:**
When a user attempts to submit a bug report using the "Report a Bug" form, the form fails to send the data to the intended server endpoint. The bug occurs because the client-side code references an incorrect URL for the API endpoint responsible for processing bug reports.

**Steps to Reproduce:**
1. Navigate to the "Report a Bug" section in Milan.
2. Fill out the bug report form with relevant details.
3. Click on the "Submit" button to send the bug report.

**Expected Behavior:**
Upon clicking the "Submit" button, the bug report should be successfully sent to the server-side API, and users should receive appropriate confirmation of the submission.

**Current Behavior:**
Upon clicking the "Submit" button, the bug report fails to be submitted due to the incorrect URL in the client-side code. As a result, users do not receive any confirmation of the submission.

**Proposed Solution:**
The bug can be fixed by updating the client-side code responsible for sending the bug report data. The URL in the client-side code should be corrected to point to the appropriate server-side API endpoint for bug reporting.

### Screenshots

![image](https://github.com/tamalCodes/Milan/assets/85815172/cf1339ea-439d-431c-a7ff-570b1349aaa2)

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by Nishitbaria** [comment]
@tamalCodes ,please assign me this issue,i will fx this and make pull request asap

**Comment by tamalCodes** [comment]
Hi @Nishitbaria, there alot of changes to be done regarding the report form, in short it will be multple changes rather than just the URL part. If you are willing to contribute should i make a new issue and close this one with proper labels and stuff ?
