### ISSUE TITLE
[FEATURE]: Convert png, jpg, svg Images File Formats  into webp File Format🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [MilanCommunity/Milan#998]
### Purpose of Raising Issue:
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**
- **I have taken an PNG Image File from Your Project directory. Observe in Screenshot, It's almost 19KB File Data Size Reduced while Converted PNG File into WEBP File Format.**
- **So, I want to work on those changes in Both Project Directory Files and Respective Codebase Files Also.**

### Screenshots
**After Conversion from PNG File Format into WEBP File Format**

![milan-2](https://github.com/tamalCodes/Milan/assets/84512164/64a2c61a-27f3-487c-9b99-924b9cd6c641)

### Screenshots

![milan-2](https://github.com/tamalCodes/Milan/assets/84512164/8443d7e9-4f04-4af3-afe1-62315dbb43bc)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/tamalCodes/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/tamalCodes/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)
- [X] I am a GSSoC23 contributor (blank for no).

**Comment by NarendraKoya999** [comment]
Hi @tamalCodes . I can Only Go with PNG, JPG Files in Both Image Files and Specific Codebases. I did not Touch SVG Files.

**Comment by NarendraKoya999** [comment]
@tamalCodes . Any Update on this Issue. There is Only One Day for Contribute 😊. Thank You !

**Comment by tamalCodes** [comment]
Hi there, i will be closing this issue since refactoring image using online tools isn't worth it. We will be making custom images later on.
